url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,body,timeline_url,performed_via_github_app,user.login,user.id,user.node_id,user.avatar_url,user.gravatar_id,user.url,user.html_url,user.followers_url,user.following_url,user.gists_url,user.starred_url,user.subscriptions_url,user.organizations_url,user.repos_url,user.events_url,user.received_events_url,user.type,user.site_admin,reactions.url,reactions.total_count,reactions.+1,reactions.-1,reactions.laugh,reactions.hooray,reactions.confused,reactions.heart,reactions.rocket,reactions.eyes,draft,pull_request.url,pull_request.html_url,pull_request.diff_url,pull_request.patch_url,pull_request.merged_at,milestone.url,milestone.html_url,milestone.labels_url,milestone.id,milestone.node_id,milestone.number,milestone.title,milestone.description,milestone.creator.login,milestone.creator.id,milestone.creator.node_id,milestone.creator.avatar_url,milestone.creator.gravatar_id,milestone.creator.url,milestone.creator.html_url,milestone.creator.followers_url,milestone.creator.following_url,milestone.creator.gists_url,milestone.creator.starred_url,milestone.creator.subscriptions_url,milestone.creator.organizations_url,milestone.creator.repos_url,milestone.creator.events_url,milestone.creator.received_events_url,milestone.creator.type,milestone.creator.site_admin,milestone.open_issues,milestone.closed_issues,milestone.state,milestone.created_at,milestone.updated_at,milestone.due_on,milestone.closed_at
https://api.github.com/repos/pandas-dev/pandas/issues/46176,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46176/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46176/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46176/events,https://github.com/pandas-dev/pandas/issues/46176,1153565414,I_kwDOAA0YD85EwgLm,46176,getsizeof  usage for memory utilization estimation is incompatible with PyPy,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-28T03:08:49Z,2022-02-28T03:08:49Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
from sklearn.datasets import fetch_openml
data = fetch_openml('mnist_784')
```


### Issue Description

PyPy doesn't like this usage of getsizeof:

```

<!--StartFragment-->

---------------------------------------------------------------------------
--
  | TypeError                                 Traceback (most recent call last)
  | ~/mambaforge-pypy3/site-packages/sklearn/datasets/_openml.py in wrapper(*args, **kw)
  | 60             try:
  | ---> 61                 return f(*args, **kw)
  | 62             except HTTPError:
  |  
  | ~/mambaforge-pypy3/site-packages/sklearn/datasets/_openml.py in _load_arff_response(url, data_home, return_type, encode_nominal, parse_arff, md5_checksum)
  | 528
  | --> 529         parsed_arff = parse_arff(arff)
  | 530
  |  
  | ~/mambaforge-pypy3/lib_pypy/_functools.py in __call__(self, *fargs, **fkeywords)
  | 79             fkeywords = dict(self._keywords, **fkeywords)
  | ---> 80         return self._func(*(self._args + fargs), **fkeywords)
  | 81
  |  
  | ~/mambaforge-pypy3/site-packages/sklearn/datasets/_openml.py in _convert_arff_data_dataframe(arff, columns, features_dict)
  | 353
  | --> 354     row_bytes = first_df.memory_usage(deep=True).sum()
  | 355     chunksize = get_chunk_n_rows(row_bytes)
  |  
  | ~/mambaforge-pypy3/site-packages/pandas/core/frame.py in memory_usage(self, index, deep)
  | 3223             result = self._constructor_sliced(
  | -> 3224                 self.index.memory_usage(deep=deep), index=[""Index""]
  | 3225             ).append(result)
  |  
  | ~/mambaforge-pypy3/site-packages/pandas/core/indexes/range.py in memory_usage(self, deep)
  | 344         """"""
  | --> 345         return self.nbytes
  | 346
  |  
  | ~/mambaforge-pypy3/site-packages/pandas/_libs/properties.pyx in pandas._libs.properties.CachedProperty.__get__()
  |  
  | ~/mambaforge-pypy3/site-packages/pandas/core/indexes/range.py in nbytes(self)
  | 316         rng = self._range
  | --> 317         return getsizeof(rng) + sum(
  | 318             getsizeof(getattr(rng, attr_name))
  |  
  | TypeError: getsizeof(...)
  | getsizeof(object, default) -> int
  |  
  | Return the size of object in bytes.
  |  
  | sys.getsizeof(object, default) will always return default on PyPy, and
  | raise a TypeError if default is not provided.
  |  
  | First note that the CPython documentation says that this function may
  | raise a TypeError, so if you are seeing it, it means that the program
  | you are using is not correctly handling this case.
  |  
  | On PyPy, though, it always raises TypeError.  Before looking for
  | alternatives, please take a moment to read the following explanation as
  | to why it is the case.  What you are looking for may not be possible.
  |  
  | A memory profiler using this function is most likely to give results
  | inconsistent with reality on PyPy.  It would be possible to have
  | sys.getsizeof() return a number (with enough work), but that may or
  | may not represent how much memory the object uses.  It doesn't even
  | make really sense to ask how much *one* object uses, in isolation
  | with the rest of the system.  For example, instances have maps,
  | which are often shared across many instances; in this case the maps
  | would probably be ignored by an implementation of sys.getsizeof(),
  | but their overhead is important in some cases if they are many
  | instances with unique maps.  Conversely, equal strings may share
  | their internal string data even if they are different objects---or
  | empty containers may share parts of their internals as long as they
  | are empty.  Even stranger, some lists create objects as you read
  | them; if you try to estimate the size in memory of range(10**6) as
  | the sum of all items' size, that operation will by itself create one
  | million integer objects that never existed in the first place.
  |  
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | TypeError                                 Traceback (most recent call last)
  | /tmp/ipykernel_18403/3646006393.py in <module>
  | ----> 1 data = fetch_openml('mnist_784')
  |  
  | ~/mambaforge-pypy3/site-packages/sklearn/datasets/_openml.py in fetch_openml(name, version, data_id, data_home, target_column, cache, return_X_y, as_frame)
  | 965         target_columns=target_columns,
  | 966         data_columns=data_columns,
  | --> 967         md5_checksum=data_description[""md5_checksum""],
  | 968     )
  | 969
  |  
  | ~/mambaforge-pypy3/site-packages/sklearn/datasets/_openml.py in _download_data_to_bunch(url, sparse, data_home, as_frame, features_list, data_columns, target_columns, shape, md5_checksum)
  | 659         encode_nominal=not as_frame,
  | 660         parse_arff=parse_arff,
  | --> 661         md5_checksum=md5_checksum,
  | 662     )
  | 663     X, y, frame, nominal_attributes = postprocess(*out)
  |  
  | ~/mambaforge-pypy3/site-packages/sklearn/datasets/_openml.py in wrapper(*args, **kw)
  | 67                 if os.path.exists(local_path):
  | 68                     os.unlink(local_path)
  | ---> 69                 return f(*args, **kw)
  | 70
  | 71         return wrapper
  |  
  | ~/mambaforge-pypy3/site-packages/sklearn/datasets/_openml.py in _load_arff_response(url, data_home, return_type, encode_nominal, parse_arff, md5_checksum)
  | 527         )
  | 528
  | --> 529         parsed_arff = parse_arff(arff)
  | 530
  | 531         # consume remaining stream, if early exited
  |  
  | ~/mambaforge-pypy3/lib_pypy/_functools.py in __call__(self, *fargs, **fkeywords)
  | 78         if self._keywords:
  | 79             fkeywords = dict(self._keywords, **fkeywords)
  | ---> 80         return self._func(*(self._args + fargs), **fkeywords)
  | 81
  | 82     @_recursive_repr()
  |  
  | ~/mambaforge-pypy3/site-packages/sklearn/datasets/_openml.py in _convert_arff_data_dataframe(arff, columns, features_dict)
  | 352     first_df = pd.DataFrame([first_row], columns=arff_columns)
  | 353
  | --> 354     row_bytes = first_df.memory_usage(deep=True).sum()
  | 355     chunksize = get_chunk_n_rows(row_bytes)
  | 356
  |  
  | ~/mambaforge-pypy3/site-packages/pandas/core/frame.py in memory_usage(self, index, deep)
  | 3222         if index:
  | 3223             result = self._constructor_sliced(
  | -> 3224                 self.index.memory_usage(deep=deep), index=[""Index""]
  | 3225             ).append(result)
  | 3226         return result
  |  
  | ~/mambaforge-pypy3/site-packages/pandas/core/indexes/range.py in memory_usage(self, deep)
  | 343         numpy.ndarray.nbytes
  | 344         """"""
  | --> 345         return self.nbytes
  | 346
  | 347     @property
  |  
  | ~/mambaforge-pypy3/site-packages/pandas/_libs/properties.pyx in pandas._libs.properties.CachedProperty.__get__()
  |  
  | ~/mambaforge-pypy3/site-packages/pandas/core/indexes/range.py in nbytes(self)
  | 315         """"""
  | 316         rng = self._range
  | --> 317         return getsizeof(rng) + sum(
  | 318             getsizeof(getattr(rng, attr_name))
  | 319             for attr_name in [""start"", ""stop"", ""step""]
  |  
  | TypeError: getsizeof(...)
  | getsizeof(object, default) -> int
  |  
  | Return the size of object in bytes.
  |  
  | sys.getsizeof(object, default) will always return default on PyPy, and
  | raise a TypeError if default is not provided.
  |  
  | First note that the CPython documentation says that this function may
  | raise a TypeError, so if you are seeing it, it means that the program
  | you are using is not correctly handling this case.
  |  
  | On PyPy, though, it always raises TypeError.  Before looking for
  | alternatives, please take a moment to read the following explanation as
  | to why it is the case.  What you are looking for may not be possible.
  |  
  | A memory profiler using this function is most likely to give results
  | inconsistent with reality on PyPy.  It would be possible to have
  | sys.getsizeof() return a number (with enough work), but that may or
  | may not represent how much memory the object uses.  It doesn't even
  | make really sense to ask how much *one* object uses, in isolation
  | with the rest of the system.  For example, instances have maps,
  | which are often shared across many instances; in this case the maps
  | would probably be ignored by an implementation of sys.getsizeof(),
  | but their overhead is important in some cases if they are many
  | instances with unique maps.  Conversely, equal strings may share
  | their internal string data even if they are different objects---or
  | empty containers may share parts of their internals as long as they
  | are empty.  Even stranger, some lists create objects as you read
  | them; if you try to estimate the size in memory of range(10**6) as
  | the sum of all items' size, that operation will by itself create one
  | million integer objects that never existed in the first place.

<!--EndFragment-->

```

### Expected Behavior

Here's an example of avoiding the usage of getsizeof elsewhere in pandas:

https://github.com/pandas-dev/pandas/blob/main/pandas/core/indexes/multi.py#L1266-L1267

### Installed Versions

<details>

To replicate this bug use mambaforge-pypy

</details>
",https://api.github.com/repos/pandas-dev/pandas/issues/46176/timeline,,mach881040,100502242,U_kgDOBf2K4g,https://avatars.githubusercontent.com/u/100502242?v=4,,https://api.github.com/users/mach881040,https://github.com/mach881040,https://api.github.com/users/mach881040/followers,https://api.github.com/users/mach881040/following{/other_user},https://api.github.com/users/mach881040/gists{/gist_id},https://api.github.com/users/mach881040/starred{/owner}{/repo},https://api.github.com/users/mach881040/subscriptions,https://api.github.com/users/mach881040/orgs,https://api.github.com/users/mach881040/repos,https://api.github.com/users/mach881040/events{/privacy},https://api.github.com/users/mach881040/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46176/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46175,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46175/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46175/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46175/events,https://github.com/pandas-dev/pandas/pull/46175,1153564804,PR_kwDOAA0YD84zoyGW,46175,PERF: avoid cast in algos.rank,[],open,False,,[],,0,2022-02-28T03:08:02Z,2022-02-28T03:08:02Z,,MEMBER,,"The real goal here is allowing us to use numeric_object_t in the libgroupby rank function, which unblocks avoiding casting in a bunch of groupby ops.",https://api.github.com/repos/pandas-dev/pandas/issues/46175/timeline,,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/8078968?v=4,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/followers,https://api.github.com/users/jbrockmendel/following{/other_user},https://api.github.com/users/jbrockmendel/gists{/gist_id},https://api.github.com/users/jbrockmendel/starred{/owner}{/repo},https://api.github.com/users/jbrockmendel/subscriptions,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/events{/privacy},https://api.github.com/users/jbrockmendel/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46175/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46175,https://github.com/pandas-dev/pandas/pull/46175,https://github.com/pandas-dev/pandas/pull/46175.diff,https://github.com/pandas-dev/pandas/pull/46175.patch,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46174,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46174/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46174/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46174/events,https://github.com/pandas-dev/pandas/pull/46174,1153468610,PR_kwDOAA0YD84zodR3,46174,PERF: faster corrwith method for pearson and spearman correlation when other is a Series and axis = 0,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance', 'name': 'Performance', 'color': 'a10c02', 'default': False, 'description': 'Memory or execution speed performance'}, {'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5NjM5OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Algos', 'name': 'Algos', 'color': 'eb6420', 'default': False, 'description': 'Non-arithmetic algos: value_counts, factorize, sorting, isin, clip, shift, diff'}]",open,False,,[],,4,2022-02-28T00:33:26Z,2022-02-28T03:13:39Z,,NONE,,"## Description of Changes

This PR modifies the `corrwith` method defined in pandas/core/frame.py to be faster when all of the following conditions are met:

- the `axis` argument is set to 0
- the `other` argument is a Pandas Series object
- the `method` argument is equal to ""pearson"" OR ""spearman""

to replace the row-wise `.apply()` with column-wise iteration on NumPy arrays and the correlation functions implemented in NumPy. If not all of those conditions are met, the method falls back to its existing functionality with no performance change.

When `method` = ""pearson"", this change reduces execution time by 40 - 50% on small and large DataFrame objects.

When `method` = ""spearman"", this change reduces execution time by 70 - 80% on small and large DataFrame objects.

This change maintains robustness to nulls despite the fact that `np.corrcoef()` is not by masking the null values across both cross objects when iterating the vectors. It returns accurate results.

## Testing Environment & Performance Assessment

My testing environment is as follows:

- Hardware: MacBook Pro (16-inc, 2021) with Apple M1 Max Chip and 64GB RAM
- OS: macOS Monterey v12.2
- Python: 3.8.12
- Pandas: v1.41 (Control, Unmodified) and v1.5.0.dev (Self-Built Test)
- NumPy: v1.22.2
- Installer/Package Manager: Anaconda3 (miniforge3 for Apple Silicon/arm64)

My test script was the following:

```
import timeit
import numpy as np
import pandas as pd

pearson_results = np.array([])
spearman_results = np.array([])
num_tests = 10
num_runs = 10

for k in range(num_tests):
    print(f'Running test {k + 1}...')
    data = np.random.uniform(-1, 1, size=(100, 50000))
    df = pd.DataFrame(data)
    df.columns = [str(c) for c in df.columns]
    pearson_time = timeit.timeit(""df.corrwith(df['0'], axis=0, method='pearson')"", ""from __main__ import df"", number=num_runs, timer=timeit.default_timer)
    spearman_time = timeit.timeit(""df.corrwith(df['0'], axis=0, method='spearman')"", ""from __main__ import df"", number=num_runs, timer=timeit.default_timer)
    pearson_results = np.append(pearson_results, pearson_time)
    spearman_results = np.append(spearman_results, spearman_time)

print(f'Average Pearson Correlation Time Across {num_tests} DataFrames with {num_runs} runs each: {pearson_results.mean() / num_runs}')
print(f'Average Spearman Correlation Time Across {num_tests} DataFrames {num_runs} runs each: {spearman_results.mean() / num_runs}')
```

First I created a fresh conda environment with the current stable version of Pandas (v1.41). For a DataFrame with 100 rows and 50,000 columns, using unmodified `.corr()` with `method=""pearson""` took approximately 3.0697 seconds on average across 10 runs each on 10 different randomly generated DataFrames. With `method=""spearman""`, the same evaluation took approximately 8.5808 seconds on average.

Then I made my changes to my fork of Pandas main and built it in a new Conda environment, then ran the same script.
For an equivalently sized DataFrame with random numerical data, the modified `.corr()` with `method=""pearson""` took approximately 1.5342 seconds. With `method=""spearman""`, it took approximately 2.0556 seconds.

## Automated Test Results

I ran `pre-commit run --files pandas/core/frame.py` and had the following results (all passed or skipped):

```
absolufy-imports................................................................................................Passed
vulture.........................................................................................................Passed
black...........................................................................................................Passed
codespell.......................................................................................................Passed
debug statements (python).......................................................................................Passed
fix end of files................................................................................................Passed
trim trailing whitespace........................................................................................Passed
cpplint.....................................................................................(no files to check)Skipped
flake8..........................................................................................................Passed
isort...........................................................................................................Passed
pyupgrade.......................................................................................................Passed
rst ``code`` is two backticks...............................................................(no files to check)Skipped
rst directives end with two colons..............................................................................Passed
rst ``inline code`` next to normal text.........................................................................Passed
Strip unnecessary `# noqa`s.....................................................................................Passed
flake8-rst..................................................................................(no files to check)Skipped
Unwanted patterns...............................................................................................Passed
Check Cython casting is `<type>obj`, not `<type> obj`.......................................(no files to check)Skipped
Check for backticks incorrectly rendering because of missing spaces.........................(no files to check)Skipped
Check for unnecessary random seeds in asv benchmarks........................................(no files to check)Skipped
Check for usage of numpy testing or array_equal.............................................(no files to check)Skipped
Check for invalid EA testing................................................................(no files to check)Skipped
Generate pip dependency from conda..........................................................(no files to check)Skipped
Check flake8 version is synced across flake8, yesqa, and environment.yml....................(no files to check)Skipped
Validate correct capitalization among titles in documentation...............................(no files to check)Skipped
Import pandas.array as pd_array in core.........................................................................Passed
Use bool_t instead of bool in pandas/core/generic.py........................................(no files to check)Skipped
Ensure pandas errors are documented in doc/source/reference/general_utility_functions.rst...(no files to check)Skipped
Check for pg8000 not installed on CI for test_pg8000_sqlalchemy_passthrough_error...........(no files to check)Skipped
Check minimum version of dependencies are aligned...........................................(no files to check)Skipped
```
",https://api.github.com/repos/pandas-dev/pandas/issues/46174/timeline,,fractionalhare,10540830,MDQ6VXNlcjEwNTQwODMw,https://avatars.githubusercontent.com/u/10540830?v=4,,https://api.github.com/users/fractionalhare,https://github.com/fractionalhare,https://api.github.com/users/fractionalhare/followers,https://api.github.com/users/fractionalhare/following{/other_user},https://api.github.com/users/fractionalhare/gists{/gist_id},https://api.github.com/users/fractionalhare/starred{/owner}{/repo},https://api.github.com/users/fractionalhare/subscriptions,https://api.github.com/users/fractionalhare/orgs,https://api.github.com/users/fractionalhare/repos,https://api.github.com/users/fractionalhare/events{/privacy},https://api.github.com/users/fractionalhare/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46174/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46174,https://github.com/pandas-dev/pandas/pull/46174,https://github.com/pandas-dev/pandas/pull/46174.diff,https://github.com/pandas-dev/pandas/pull/46174.patch,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46173,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46173/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46173/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46173/events,https://github.com/pandas-dev/pandas/issues/46173,1153437571,I_kwDOAA0YD85EwA-D,46173,Missing keys in a selector list are matched to None-labeled entries of MultiIndex,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-27T23:07:07Z,2022-02-28T00:02:22Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame.from_dict({
    (""foo"",): [1, 2, 3],
    (""bar"",): [5, 6, 7],
    (None,): [8, 9, 0], 
})
df[[ (""missingKey"",) ]] # returns the NaN-labeled column [8, 9, 0] instead of raising a KeyError
```


### Issue Description

Given a DataFrame with MultiIndex containing NaN values in its keys, then keys with missing labels on the same level as NaN values will retrieve the NaN-labeled columns if keys are passed in a list.

If multiple missing labels are passed, each of them will retrieve the None column
```python
pd.DataFrame.from_dict({(None,): [8, 9, 0]}).loc[:, [(""foo"",), (""bar"",)]]  # returns a DF with two copies of the NaN-labeled [8, 9, 0] column 
``` 

This behaviour occurs only when selection is done via a list of keys. 
```python
pd.DataFrame.from_dict({(None,): [8, 9, 0]}).loc[:, (""foo"",)]  # single key - raises KeyError
pd.DataFrame.from_dict({(None,): [8, 9, 0]}).loc[:, [(""foo"",)]]  # key in a list - returns [8,9,0]
```

The same issue occurs for multi-level MultiIndex, as long as missing labels in the selector occur only on the same level as NaN values.
```python
pd.DataFrame.from_dict({(None,None): [8, 9, 0]}).loc[:, [(""a"",""a"")]]  # returns [8, 9, 0]
pd.DataFrame.from_dict({(None,None): [8, 9, 0]}).loc[:, [(""a"",""b"")]]  # returns [8, 9, 0]
pd.DataFrame.from_dict({(None,""b""): [8, 9, 0]}).loc[:, [(""a"",""b"")]]  # returns [8, 9, 0]
pd.DataFrame.from_dict({(None,""a""): [8, 9, 0]}).loc[:, [(""a"",""b"")]]  # KeyError, because 2nd level didn't match
```

`None` can also be replaced with any of `pd.NA`, `np.nan`, `pd.NaT` for the same effect. 

An additional, more complex example, with multiple `None` in index.
```python
dataframe = pd.DataFrame.from_dict({
    (None,None): [1, 2, 3],
    (None,""a""): [5, 6, 7],
    (""b"",None): [8, 9, 0],
})

df[[(""foo"", ""bar"")]] # returns [1,2,3]
df[[(""foo"", ""a"")]] # returns [5,6,7]
df[[(""b ""foo"")]] # returns [8,9,0]
df[[(""b"",""a"")]] # raises KeyError!
```
Interestingly enough, if `[(""a"", ""b"")]` is used to select from this DF, a KeyError *will* be raised, instead of matching it to (None, None).


### Expected Behavior

A KeyError should be raised, as it would be if the key with missing label was not wrapped in a list.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.13.0-27-generic
Version          : #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 20.0.2
setuptools       : 44.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 8.0.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.4.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>
",https://api.github.com/repos/pandas-dev/pandas/issues/46173/timeline,,macsakow,10297014,MDQ6VXNlcjEwMjk3MDE0,https://avatars.githubusercontent.com/u/10297014?v=4,,https://api.github.com/users/macsakow,https://github.com/macsakow,https://api.github.com/users/macsakow/followers,https://api.github.com/users/macsakow/following{/other_user},https://api.github.com/users/macsakow/gists{/gist_id},https://api.github.com/users/macsakow/starred{/owner}{/repo},https://api.github.com/users/macsakow/subscriptions,https://api.github.com/users/macsakow/orgs,https://api.github.com/users/macsakow/repos,https://api.github.com/users/macsakow/events{/privacy},https://api.github.com/users/macsakow/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46173/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46172,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46172/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46172/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46172/events,https://github.com/pandas-dev/pandas/pull/46172,1153427536,PR_kwDOAA0YD84zoUoF,46172,"REF: implement _reconstruct_ea_result, _ea_to_cython_values","[{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2ODE=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Refactor', 'name': 'Refactor', 'color': 'FCE94F', 'default': False, 'description': 'Internal refactoring of code'}]",open,False,,[],,0,2022-02-27T22:35:48Z,2022-02-28T03:49:41Z,,MEMBER,,"The idea being to eventually refactor those into EA/EADtype methods, xref #43682
",https://api.github.com/repos/pandas-dev/pandas/issues/46172/timeline,,jbrockmendel,8078968,MDQ6VXNlcjgwNzg5Njg=,https://avatars.githubusercontent.com/u/8078968?v=4,,https://api.github.com/users/jbrockmendel,https://github.com/jbrockmendel,https://api.github.com/users/jbrockmendel/followers,https://api.github.com/users/jbrockmendel/following{/other_user},https://api.github.com/users/jbrockmendel/gists{/gist_id},https://api.github.com/users/jbrockmendel/starred{/owner}{/repo},https://api.github.com/users/jbrockmendel/subscriptions,https://api.github.com/users/jbrockmendel/orgs,https://api.github.com/users/jbrockmendel/repos,https://api.github.com/users/jbrockmendel/events{/privacy},https://api.github.com/users/jbrockmendel/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46172/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46172,https://github.com/pandas-dev/pandas/pull/46172,https://github.com/pandas-dev/pandas/pull/46172.diff,https://github.com/pandas-dev/pandas/pull/46172.patch,,https://api.github.com/repos/pandas-dev/pandas/milestones/92,https://github.com/pandas-dev/pandas/milestone/92,https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels,7530006.0,MI_kwDOAA0YD84AcuYW,92.0,1.5,,jreback,953992.0,MDQ6VXNlcjk1Mzk5Mg==,https://avatars.githubusercontent.com/u/953992?v=4,,https://api.github.com/users/jreback,https://github.com/jreback,https://api.github.com/users/jreback/followers,https://api.github.com/users/jreback/following{/other_user},https://api.github.com/users/jreback/gists{/gist_id},https://api.github.com/users/jreback/starred{/owner}{/repo},https://api.github.com/users/jreback/subscriptions,https://api.github.com/users/jreback/orgs,https://api.github.com/users/jreback/repos,https://api.github.com/users/jreback/events{/privacy},https://api.github.com/users/jreback/received_events,User,False,51.0,401.0,open,2021-12-31T21:51:13Z,2022-02-28T00:39:54Z,2022-06-30T07:00:00Z,
https://api.github.com/repos/pandas-dev/pandas/issues/46171,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46171/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46171/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46171/events,https://github.com/pandas-dev/pandas/pull/46171,1153397978,PR_kwDOAA0YD84zoOh4,46171,TYP: remove NaTType as possible result of Timestamp and Timedelta constructor,"[{'id': 49597148, 'node_id': 'MDU6TGFiZWw0OTU5NzE0OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timedelta', 'name': 'Timedelta', 'color': '5319e7', 'default': False, 'description': 'Timedelta data type'}, {'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMjgwOTg4NDI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Typing', 'name': 'Typing', 'color': 'ea91a4', 'default': False, 'description': 'type annotations, mypy/pyright type checking'}, {'id': 3877216987, 'node_id': 'LA_kwDOAA0YD87nGaLb', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timestamp', 'name': 'Timestamp', 'color': '5DE3E8', 'default': False, 'description': 'Cod related to pd.Timestamp'}]",open,False,,[],,4,2022-02-27T21:00:33Z,2022-02-28T05:29:38Z,,CONTRIBUTOR,,"While working on the Microsoft type stubs, I discovered this.  With the current code, if you run `pyright` on the following with default settings for basic type checking (not using what we have in `pyproject.toml`):
```python
import pandas as pd
print(""version "", pd.__version__)
ts:pd.Timestamp =  pd.Timestamp(""2022-02-27"")
print(ts)
```
you get this:
```
c:\Code\pandas_dev\pandas\tstest.py
  c:\Code\pandas_dev\pandas\tstest.py:3:20 - error: Expression of type ""Timestamp | NaTType"" cannot be assigned to declared type ""Timestamp""
    Type ""Timestamp | NaTType"" cannot be assigned to type ""Timestamp""
      ""NaTType"" is incompatible with ""Timestamp"" (reportGeneralTypeIssues)
```
`mypy` doesn't pick this up.  The real issue here is that you generally expect a `Timestamp` constructor to return a `Timestamp`, so by returning the `Union`, we are then forcing end users to `cast` the result of the constructor, which is pretty inconvenient.

So even though the constructor _could_ return a `NaTType`, we shouldn't force users to code for that due to static type checking.

This PR just takes out the `NaTType` as a return type for the constructors.
",https://api.github.com/repos/pandas-dev/pandas/issues/46171/timeline,,Dr-Irv,15113894,MDQ6VXNlcjE1MTEzODk0,https://avatars.githubusercontent.com/u/15113894?v=4,,https://api.github.com/users/Dr-Irv,https://github.com/Dr-Irv,https://api.github.com/users/Dr-Irv/followers,https://api.github.com/users/Dr-Irv/following{/other_user},https://api.github.com/users/Dr-Irv/gists{/gist_id},https://api.github.com/users/Dr-Irv/starred{/owner}{/repo},https://api.github.com/users/Dr-Irv/subscriptions,https://api.github.com/users/Dr-Irv/orgs,https://api.github.com/users/Dr-Irv/repos,https://api.github.com/users/Dr-Irv/events{/privacy},https://api.github.com/users/Dr-Irv/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46171/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46171,https://github.com/pandas-dev/pandas/pull/46171,https://github.com/pandas-dev/pandas/pull/46171.diff,https://github.com/pandas-dev/pandas/pull/46171.patch,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46170,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46170/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46170/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46170/events,https://github.com/pandas-dev/pandas/pull/46170,1153354336,PR_kwDOAA0YD84zoFw0,46170,DOC: Remove computation.rst in favor of better docstrings,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}]",open,False,,[],,1,2022-02-27T18:42:52Z,2022-02-28T02:26:49Z,,MEMBER,,"- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

This page seemed unmaintained and stale relative to the 4 functions this page goes over.

Instead of trying to maintain documentation of these functions in 2 places, just improves the docstrings of the functions where information diverged.
",https://api.github.com/repos/pandas-dev/pandas/issues/46170/timeline,,mroeschke,10647082,MDQ6VXNlcjEwNjQ3MDgy,https://avatars.githubusercontent.com/u/10647082?v=4,,https://api.github.com/users/mroeschke,https://github.com/mroeschke,https://api.github.com/users/mroeschke/followers,https://api.github.com/users/mroeschke/following{/other_user},https://api.github.com/users/mroeschke/gists{/gist_id},https://api.github.com/users/mroeschke/starred{/owner}{/repo},https://api.github.com/users/mroeschke/subscriptions,https://api.github.com/users/mroeschke/orgs,https://api.github.com/users/mroeschke/repos,https://api.github.com/users/mroeschke/events{/privacy},https://api.github.com/users/mroeschke/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46170/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46170,https://github.com/pandas-dev/pandas/pull/46170,https://github.com/pandas-dev/pandas/pull/46170.diff,https://github.com/pandas-dev/pandas/pull/46170.patch,,https://api.github.com/repos/pandas-dev/pandas/milestones/92,https://github.com/pandas-dev/pandas/milestone/92,https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels,7530006.0,MI_kwDOAA0YD84AcuYW,92.0,1.5,,jreback,953992.0,MDQ6VXNlcjk1Mzk5Mg==,https://avatars.githubusercontent.com/u/953992?v=4,,https://api.github.com/users/jreback,https://github.com/jreback,https://api.github.com/users/jreback/followers,https://api.github.com/users/jreback/following{/other_user},https://api.github.com/users/jreback/gists{/gist_id},https://api.github.com/users/jreback/starred{/owner}{/repo},https://api.github.com/users/jreback/subscriptions,https://api.github.com/users/jreback/orgs,https://api.github.com/users/jreback/repos,https://api.github.com/users/jreback/events{/privacy},https://api.github.com/users/jreback/received_events,User,False,51.0,401.0,open,2021-12-31T21:51:13Z,2022-02-28T00:39:54Z,2022-06-30T07:00:00Z,
https://api.github.com/repos/pandas-dev/pandas/issues/46167,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46167/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46167/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46167/events,https://github.com/pandas-dev/pandas/pull/46167,1153244393,PR_kwDOAA0YD84znvRb,46167,Bug fix - rename dataframe reset index,[],open,False,,[],,1,2022-02-27T13:06:18Z,2022-02-27T22:55:16Z,,CONTRIBUTOR,,"- [ ] closes #6878
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",https://api.github.com/repos/pandas-dev/pandas/issues/46167/timeline,,weikhor,36619387,MDQ6VXNlcjM2NjE5Mzg3,https://avatars.githubusercontent.com/u/36619387?v=4,,https://api.github.com/users/weikhor,https://github.com/weikhor,https://api.github.com/users/weikhor/followers,https://api.github.com/users/weikhor/following{/other_user},https://api.github.com/users/weikhor/gists{/gist_id},https://api.github.com/users/weikhor/starred{/owner}{/repo},https://api.github.com/users/weikhor/subscriptions,https://api.github.com/users/weikhor/orgs,https://api.github.com/users/weikhor/repos,https://api.github.com/users/weikhor/events{/privacy},https://api.github.com/users/weikhor/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46167/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46167,https://github.com/pandas-dev/pandas/pull/46167,https://github.com/pandas-dev/pandas/pull/46167.diff,https://github.com/pandas-dev/pandas/pull/46167.patch,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46166,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46166/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46166/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46166/events,https://github.com/pandas-dev/pandas/pull/46166,1152939467,PR_kwDOAA0YD84zmo39,46166,Enable server side cursors,"[{'id': 47232590, 'node_id': 'MDU6TGFiZWw0NzIzMjU5MA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20SQL', 'name': 'IO SQL', 'color': '5319e7', 'default': False, 'description': 'to_sql, read_sql, read_sql_query'}]",open,False,,[],,0,2022-02-27T06:48:36Z,2022-02-27T20:15:13Z,,NONE,,"The old PR went stale and I ended up busy for a year so had to re-open in a new branch. Hoping to finally push this through

This pull request attempts to fix #35689.  I read an article by @itamarst and decided to look further into the codebase. After noticing that the fix semed to be simple I decided file a PR. The fix is naive and I'm not sure the true solution is as simple as I imagine it to be. There are probably many things I'm missing as I've not read the codebase in detail so do let me know what else needs to be addressed.

- [x] closes #35689
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry(N.A.)",https://api.github.com/repos/pandas-dev/pandas/issues/46166/timeline,,J0,8011761,MDQ6VXNlcjgwMTE3NjE=,https://avatars.githubusercontent.com/u/8011761?v=4,,https://api.github.com/users/J0,https://github.com/J0,https://api.github.com/users/J0/followers,https://api.github.com/users/J0/following{/other_user},https://api.github.com/users/J0/gists{/gist_id},https://api.github.com/users/J0/starred{/owner}{/repo},https://api.github.com/users/J0/subscriptions,https://api.github.com/users/J0/orgs,https://api.github.com/users/J0/repos,https://api.github.com/users/J0/events{/privacy},https://api.github.com/users/J0/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46166/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46166,https://github.com/pandas-dev/pandas/pull/46166,https://github.com/pandas-dev/pandas/pull/46166.diff,https://github.com/pandas-dev/pandas/pull/46166.patch,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46164,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46164/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46164/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46164/events,https://github.com/pandas-dev/pandas/issues/46164,1152647346,I_kwDOAA0YD85EtACy,46164,BUG: Index.equals different behavior for EA vs non-EA types,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDkwMjM2OTM=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ExtensionArray', 'name': 'ExtensionArray', 'color': '6138b5', 'default': False, 'description': 'Extending pandas with custom dtypes or arrays.'}, {'id': 1218227310, 'node_id': 'MDU6TGFiZWwxMjE4MjI3MzEw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Index', 'name': 'Index', 'color': 'e99695', 'default': False, 'description': 'Related to the Index class or subclasses'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-27T02:12:17Z,2022-02-27T02:18:29Z,,CONTRIBUTOR,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

f32 = pd.Index([1,2,3], dtype='float32')
f64 = pd.Index([1,2,3], dtype='float64')
F32 = pd.Index([1,2,3], dtype='Float32')
F64 = pd.Index([1,2,3], dtype='Float64')

>>> f32.equals(f64)
True

>>> F32.equals(F64)
False
```


### Issue Description

The docs for `Index.equals` state that the dtype is not part of the equality test between indexes. The last example in the docs shows indexes with different dtypes being considered equal.  

https://pandas.pydata.org/docs/reference/api/pandas.Index.equals.html

However, in the case of EA types the behavior is different and dtype does seem to be part of the equality check. 

### Expected Behavior

I'm not sure whether the different behavior between EA and non-EA types is actually a bug. Maybe it is expected in which case it should be mentioned in the docs?

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 90d32204ced71ea9f93fee3e271a6081d25a73c8
python           : 3.8.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.10.16.3-microsoft-standard-WSL2
Version          : #1 SMP Fri Apr 2 22:23:49 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+449.g90d32204ce
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 60.5.0
Cython           : 0.29.26
pytest           : 6.2.5
hypothesis       : 6.36.0
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.7.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fastparquet      : 0.7.2
fsspec           : 2021.11.0
gcsfs            : 2021.11.0
markupsafe       : 2.0.1
matplotlib       : 3.5.1
numba            : 0.55.0
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : 1.1.4
pyxlsb           : None
s3fs             : 2021.11.0
scipy            : 1.7.3
sqlalchemy       : 1.4.31
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>
",https://api.github.com/repos/pandas-dev/pandas/issues/46164/timeline,,lukemanley,8519523,MDQ6VXNlcjg1MTk1MjM=,https://avatars.githubusercontent.com/u/8519523?v=4,,https://api.github.com/users/lukemanley,https://github.com/lukemanley,https://api.github.com/users/lukemanley/followers,https://api.github.com/users/lukemanley/following{/other_user},https://api.github.com/users/lukemanley/gists{/gist_id},https://api.github.com/users/lukemanley/starred{/owner}{/repo},https://api.github.com/users/lukemanley/subscriptions,https://api.github.com/users/lukemanley/orgs,https://api.github.com/users/lukemanley/repos,https://api.github.com/users/lukemanley/events{/privacy},https://api.github.com/users/lukemanley/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46164/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46162,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46162/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46162/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46162/events,https://github.com/pandas-dev/pandas/pull/46162,1151916356,PR_kwDOAA0YD84zi3lJ,46162,Bug fix - GroupBy.describe produces inconsistent results for empty datasets,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 13098779, 'node_id': 'MDU6TGFiZWwxMzA5ODc3OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping', 'name': 'Reshaping', 'color': '02d7e1', 'default': False, 'description': 'Concat, Merge/Join, Stack/Unstack, Explode'}]",open,False,,[],,0,2022-02-26T15:55:59Z,2022-02-27T16:34:23Z,,CONTRIBUTOR,,"- [x] closes #41575
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",https://api.github.com/repos/pandas-dev/pandas/issues/46162/timeline,,weikhor,36619387,MDQ6VXNlcjM2NjE5Mzg3,https://avatars.githubusercontent.com/u/36619387?v=4,,https://api.github.com/users/weikhor,https://github.com/weikhor,https://api.github.com/users/weikhor/followers,https://api.github.com/users/weikhor/following{/other_user},https://api.github.com/users/weikhor/gists{/gist_id},https://api.github.com/users/weikhor/starred{/owner}{/repo},https://api.github.com/users/weikhor/subscriptions,https://api.github.com/users/weikhor/orgs,https://api.github.com/users/weikhor/repos,https://api.github.com/users/weikhor/events{/privacy},https://api.github.com/users/weikhor/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46162/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46162,https://github.com/pandas-dev/pandas/pull/46162,https://github.com/pandas-dev/pandas/pull/46162.diff,https://github.com/pandas-dev/pandas/pull/46162.patch,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46156,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46156/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46156/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46156/events,https://github.com/pandas-dev/pandas/pull/46156,1150920527,PR_kwDOAA0YD84zfScw,46156,BUG: MultiIndex slicing with negative step,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}, {'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2ODMzMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/MultiIndex', 'name': 'MultiIndex', 'color': '207de5', 'default': False, 'description': None}]",open,False,,[],,1,2022-02-25T22:06:34Z,2022-02-26T20:50:27Z,,CONTRIBUTOR,,"- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest `doc/source/whatsnew/v1.5.0.rst` file if fixing a bug or adding a new feature.

MultiIndex label-based (.loc) slicing with a _negative_ step size appears to contain a few bugs. 

#38071 may have partially addressed negative step size issues, but a few issues seem to remain. 

I believe this PR fixes the following:


Bug 1: slicing with non-null start/stop values returns an empty frame

```
    from pandas import DataFrame, IndexSlice, MultiIndex

    mi = MultiIndex.from_arrays([range(5)] * 2)
    df = DataFrame(1.0, index=mi, columns=['A'])

    target = IndexSlice[3:1:-1, :]
    df.loc[target, :]
```

Bug 2: negative step size other than -1 raises

```
    from pandas import DataFrame, IndexSlice, MultiIndex

    mi = MultiIndex.from_arrays([range(5)] * 2)
    df = DataFrame(1.0, index=mi, columns=['A'])

    target = IndexSlice[::-2, :]
    df.loc[target, :]
```

Bug 3: slicing a non-int labeled index level raises

```
    from pandas import DataFrame, IndexSlice, MultiIndex

    mi = MultiIndex.from_arrays([list('abcde')] * 2)
    df = DataFrame(1.0, index=mi, columns=['A'])

    target = IndexSlice['d':'b':-1, :]
    df.loc[target, :]
```

The tests have been expanded to cover these cases.",https://api.github.com/repos/pandas-dev/pandas/issues/46156/timeline,,lukemanley,8519523,MDQ6VXNlcjg1MTk1MjM=,https://avatars.githubusercontent.com/u/8519523?v=4,,https://api.github.com/users/lukemanley,https://github.com/lukemanley,https://api.github.com/users/lukemanley/followers,https://api.github.com/users/lukemanley/following{/other_user},https://api.github.com/users/lukemanley/gists{/gist_id},https://api.github.com/users/lukemanley/starred{/owner}{/repo},https://api.github.com/users/lukemanley/subscriptions,https://api.github.com/users/lukemanley/orgs,https://api.github.com/users/lukemanley/repos,https://api.github.com/users/lukemanley/events{/privacy},https://api.github.com/users/lukemanley/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46156/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46156,https://github.com/pandas-dev/pandas/pull/46156,https://github.com/pandas-dev/pandas/pull/46156.diff,https://github.com/pandas-dev/pandas/pull/46156.patch,,https://api.github.com/repos/pandas-dev/pandas/milestones/92,https://github.com/pandas-dev/pandas/milestone/92,https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels,7530006.0,MI_kwDOAA0YD84AcuYW,92.0,1.5,,jreback,953992.0,MDQ6VXNlcjk1Mzk5Mg==,https://avatars.githubusercontent.com/u/953992?v=4,,https://api.github.com/users/jreback,https://github.com/jreback,https://api.github.com/users/jreback/followers,https://api.github.com/users/jreback/following{/other_user},https://api.github.com/users/jreback/gists{/gist_id},https://api.github.com/users/jreback/starred{/owner}{/repo},https://api.github.com/users/jreback/subscriptions,https://api.github.com/users/jreback/orgs,https://api.github.com/users/jreback/repos,https://api.github.com/users/jreback/events{/privacy},https://api.github.com/users/jreback/received_events,User,False,51.0,401.0,open,2021-12-31T21:51:13Z,2022-02-28T00:39:54Z,2022-06-30T07:00:00Z,
https://api.github.com/repos/pandas-dev/pandas/issues/46154,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46154/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46154/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46154/events,https://github.com/pandas-dev/pandas/issues/46154,1150876170,I_kwDOAA0YD85EmPoK,46154,BUG: Converting `pd.Timestamp.min` to equivalent pydatetime object and back raises `OutOfBoundsDatetime`,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2022-02-25T20:58:54Z,2022-02-26T01:07:28Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

min_timestamp = pd.Timestamp.min
min_pydatetime = min_timestamp.to_pydatetime()
min_datetime = pd.to_datetime(min_pydatetime)
print(min_datetime)  # just to provide script output
```


### Issue Description

Going from `pd.Timestamp.min` to the equivalent `datetime.datetime` instance and back works with pandas v1.2.5 but fails in v1.3.0 (and all subsequent versions) due to an out of bounds error. This behavior is unchanged in the current main branch:

<details>
<summary>See traceback for version <code>1.5.0.dev0+396.geaefc5c416</code></summary>

```zsh
sys:1: UserWarning: Discarding nonzero nanoseconds in conversion
Traceback (most recent call last):
  File ""/Users/milotoor/.pyenv/versions/pandas_1_3_0/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py"", line 2187, in objects_to_datetime64ns
    values, tz_parsed = conversion.datetime_to_datetime64(data.ravel(""K""))
  File ""pandas/_libs/tslibs/conversion.pyx"", line 357, in pandas._libs.tslibs.conversion.datetime_to_datetime64
  File ""pandas/_libs/tslibs/np_datetime.pyx"", line 120, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1677-09-21 00:12:43

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ""/Users/milotoor/tslib_bug_demo.py"", line 5, in <module>
    min_datetime = pd.to_datetime(min_pydatetime)
  File ""/Users/milotoor/.pyenv/versions/pandas_1_3_0/lib/python3.9/site-packages/pandas/core/tools/datetimes.py"", line 914, in to_datetime
    result = convert_listlike(np.array([arg]), format)[0]
  File ""/Users/milotoor/.pyenv/versions/pandas_1_3_0/lib/python3.9/site-packages/pandas/core/tools/datetimes.py"", line 401, in _convert_listlike_datetimes
    result, tz_parsed = objects_to_datetime64ns(
  File ""/Users/milotoor/.pyenv/versions/pandas_1_3_0/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py"", line 2193, in objects_to_datetime64ns
    raise err
  File ""/Users/milotoor/.pyenv/versions/pandas_1_3_0/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py"", line 2175, in objects_to_datetime64ns
    result, tz_parsed = tslib.array_to_datetime(
  File ""pandas/_libs/tslib.pyx"", line 379, in pandas._libs.tslib.array_to_datetime
  File ""pandas/_libs/tslib.pyx"", line 606, in pandas._libs.tslib.array_to_datetime
  File ""pandas/_libs/tslib.pyx"", line 602, in pandas._libs.tslib.array_to_datetime
  File ""pandas/_libs/tslib.pyx"", line 474, in pandas._libs.tslib.array_to_datetime
  File ""pandas/_libs/tslibs/np_datetime.pyx"", line 120, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1677-09-21 00:12:43
```

I'm not sure what to make of the ""Discarding nonzero nanoseconds in conversion"" warning above the traceback.
</details>

I believe this regression was introduced in #39245, which modifies the `_NS_MIN_DTS` const value:

```diff
➜  pandas git:(main) git df v1.2.5 v1.3.0 -- pandas/_libs/tslibs/src

diff --git a/pandas/_libs/tslibs/src/datetime/np_datetime.c b/pandas/_libs/tslibs/src/datetime/np_datetime.c
index 8eb995dee6..9ad2ead5f9 100644
--- a/pandas/_libs/tslibs/src/datetime/np_datetime.c
+++ b/pandas/_libs/tslibs/src/datetime/np_datetime.c
@@ -32,7 +32,7 @@ This file is derived from NumPy 1.7. See NUMPY_LICENSE.txt
 #endif  // PyInt_AsLong

 const npy_datetimestruct _NS_MIN_DTS = {
-    1677, 9, 21, 0, 12, 43, 145225, 0, 0};
+    1677, 9, 21, 0, 12, 43, 145224, 193000, 0};
 const npy_datetimestruct _NS_MAX_DTS = {
     2262, 4, 11, 23, 47, 16, 854775, 807000, 0};
```

### Expected Behavior

The script above should print out the datetime as a string. Pandas v1.2.5 does the following:

```zsh
➜  ~ cat tslib_bug_demo.py
import pandas as pd

min_timestamp = pd.Timestamp.min
min_pydatetime = min_timestamp.to_pydatetime()
min_datetime = pd.to_datetime(min_pydatetime)
print(min_datetime)

➜  ~ pyenv activate pandas_1_2_5
(pandas_1_2_5) ➜  ~ python --version
Python 3.9.10
(pandas_1_2_5) ➜  ~ pip list | grep pandas
pandas          1.2.5
(pandas_1_2_5) ➜  ~ python tslib_bug_demo.py
1677-09-21 00:12:43.145225
```

### Installed Versions

<details>
<summary>Versions for <code>v1.2.5</code></summary>

```
commit           : 7c48ff4409c622c582c56a5702373f726de08e96
python           : 3.9.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.3.0
Version          : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.2.5
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 58.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
```
</details>

<details>
<summary>Versions for <code>v1.3.0</code></summary>

```
commit           : f00ed8f47020034e752baf0250483053340971b0
python           : 3.9.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.3.0
Version          : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.0
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None
```
</details>

<details>
<summary>Versions for current main branch</summary>

```
commit           : eaefc5c4160b73521f36dd04a43ea65423772b11
python           : 3.9.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.3.0
Version          : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000
machine          : arm64
processor        : arm
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+396.geaefc5c416
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
```
</details>",https://api.github.com/repos/pandas-dev/pandas/issues/46154/timeline,,milotoor,4667801,MDQ6VXNlcjQ2Njc4MDE=,https://avatars.githubusercontent.com/u/4667801?v=4,,https://api.github.com/users/milotoor,https://github.com/milotoor,https://api.github.com/users/milotoor/followers,https://api.github.com/users/milotoor/following{/other_user},https://api.github.com/users/milotoor/gists{/gist_id},https://api.github.com/users/milotoor/starred{/owner}{/repo},https://api.github.com/users/milotoor/subscriptions,https://api.github.com/users/milotoor/orgs,https://api.github.com/users/milotoor/repos,https://api.github.com/users/milotoor/events{/privacy},https://api.github.com/users/milotoor/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46154/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46152,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46152/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46152/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46152/events,https://github.com/pandas-dev/pandas/issues/46152,1150754239,I_kwDOAA0YD85Elx2_,46152,BUG: Styler cannot accept semicolon in CSS val,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1728592794, 'node_id': 'MDU6TGFiZWwxNzI4NTkyNzk0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Styler', 'name': 'Styler', 'color': '006b75', 'default': False, 'description': 'conditional formatting using DataFrame.style'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2022-02-25T18:56:12Z,2022-02-27T16:02:48Z,,CONTRIBUTOR,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({""A"": [1, 0, -1]})

css = 'text-align: left; number-format: ""0;[Red](0);-;@""; ;'

try:
    (
        df
        .style
        # Replace zero with dash, negative with red
        .applymap(lambda x: css)
        .to_excel(""test.xlsx"")
    )
except Exception as e:
    print(e)
```


### Issue Description

Styler does not accept CSS value [string types](https://developer.mozilla.org/en-US/docs/Web/CSS/string) enclosed in double quotes. In particular, it crashes if the string contains semi-colons. This means full `number-format` strings cannot be passed to `Styler` for exporting to Excel. Excel number format is of the form: `<positive>;<negative>;<zero>;<text>`. The semi-colon dividers here will conflict with CSS semi-colon dividers unless they can be properly encapsulated in a string.

The problem is rooted in the naive string split in `maybe_convert_css_to_tuples` and `CSSResolver`. A possible fix using the `TextFileReader` parser is shown in the Expected Behavior section.

### Expected Behavior

In the above example, the function should export the following sheet:

![image](https://user-images.githubusercontent.com/7980666/155769242-2515210e-5d06-4530-b056-f09b300cbb61.png)

Here is a set of changes that can produce the desired behavior using pandas parsing libraries:
```
### In style_render.py
def maybe_convert_css_to_tuples(style):
    from io import StringIO
    from pandas.io.parsers.readers import TextFileReader

    if style and isinstance(style, str):
        # Use ""C"" parser because of line terminator
        s = TextFileReader(StringIO(style), engine=""c"", delimiter="":"", lineterminator="";"", skipinitialspace=True, index=False, header=None).read()

        try:
            return [
                (row[0].strip(), row[1].strip())
                for _, row in s.iterrows()
                if row[0] != """"
            ]
        except IndexError:
            raise ValueError(
                ""Styles supplied as string must follow CSS rule formats, ""
                f""for example 'attr: val;'. '{style}' was given.""
            )
    return style

### In css.py
class CSSResolver():
    # ...
    def parse(self, declarations_str: str):
        from io import StringIO
        from pandas.io.parsers.c_parser_wrapper import CParserWrapper
        from pandas.io.parsers.readers import TextFileReader

        if (declarations_str):
            s = TextFileReader(StringIO(declarations_str), engine=""c"", delimiter="":"", lineterminator="";"", skipinitialspace=True, index=False, header=None).read()

            try:
                for _,row in s.iterrows():
                    prop, val = row[0], row[1]

                    prop = prop.strip().lower()
                    # TODO: don't lowercase case sensitive parts of values (strings)
                    val = val.strip().lower()

                    yield prop, val
            except Exception as e:
                print(e)

### In io/formats/excel.py
class CssExcelCell(ExcelCell):
    def __init__(
        self,
        row: int,
        col: int,
        val,
        style: dict | None,
        css_styles: dict[tuple[int, int], list[tuple[str, Any]]] | None,
        css_row: int,
        css_col: int,
        css_converter: Callable | None,
        **kwargs,
    ):
        if css_styles and css_converter:
            # Not exhaustively tested. Might be better to add quotes conditionally based on type of `v`
            css = "";"".join(a + "":"" + ""\"""" + str(v) + ""\"""" for (a, v) in css_styles[css_row, css_col])
            style = css_converter(css)

        return super().__init__(row=row, col=col, val=val, style=style, **kwargs)
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.10.1.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
...
pandas           : 1.4.1
numpy            : 1.22.0
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 60.2.0
Cython           : None
pytest           : 7.0.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.0
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : None
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None
</details>
",https://api.github.com/repos/pandas-dev/pandas/issues/46152/timeline,,tehunter,7980666,MDQ6VXNlcjc5ODA2NjY=,https://avatars.githubusercontent.com/u/7980666?v=4,,https://api.github.com/users/tehunter,https://github.com/tehunter,https://api.github.com/users/tehunter/followers,https://api.github.com/users/tehunter/following{/other_user},https://api.github.com/users/tehunter/gists{/gist_id},https://api.github.com/users/tehunter/starred{/owner}{/repo},https://api.github.com/users/tehunter/subscriptions,https://api.github.com/users/tehunter/orgs,https://api.github.com/users/tehunter/repos,https://api.github.com/users/tehunter/events{/privacy},https://api.github.com/users/tehunter/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46152/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46149,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46149/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46149/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46149/events,https://github.com/pandas-dev/pandas/issues/46149,1150712051,I_kwDOAA0YD85Elnjz,46149,PERF: Series.fillna (that is part of DataFrame) with inplace=True high memory usage / memory leaking,"[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance', 'name': 'Performance', 'color': 'a10c02', 'default': False, 'description': 'Memory or execution speed performance'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2022-02-25T17:58:09Z,2022-02-28T00:35:49Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this issue exists on the main branch of pandas.


### Reproducible Example

I have recently migrated from pandas `1.1.3` to pandas `1.4.1` and I'm experiencing some memory-related issues. The code that used to work just fine is now crashing due to memory limitations.

Reproducible example:
```
import pandas as pd
import numpy as np

df = pd.DataFrame([[np.nan] * 400]*500000)

for col in df.columns:
    df[col].fillna(-1, inplace=True)
```

Interestingly enough, this snippet, which I would expect to have bigger memory requirements (as it's not inplace), works just fine:
```
import pandas as pd
import numpy as np

df = pd.DataFrame([[np.nan] * 400]*500000)

for col in df.columns:
    df[col] = df[col].fillna(-1)
```

The real code is obviously more complicated than the example, so I'd like to keep filling NA's column by column and doing this in place. Is that an unintended way of using `fillna` for `DataFrame`'s `Series` or is it a bug?
I don't have any memory profiling applied that I could share, but I can try making one if that's necessary. I've just noticed the code work in old pandas version and doesn't work in the new one, and I can see the memory usage in system's resource monitor.

### Installed Versions

```
INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.8.3.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.4.0
Version          : Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.4.1
numpy            : 1.21.0
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 22.0.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : 3.3.2
numba            : 0.53.1
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 2.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.3
sqlalchemy       : 1.4.11
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
```

### Prior Performance

In pandas 1.1.3 the first snippet works just fine.
Both snippets also seem to work incomparably faster on the older pandas version.",https://api.github.com/repos/pandas-dev/pandas/issues/46149/timeline,,jukiewiczm,8179126,MDQ6VXNlcjgxNzkxMjY=,https://avatars.githubusercontent.com/u/8179126?v=4,,https://api.github.com/users/jukiewiczm,https://github.com/jukiewiczm,https://api.github.com/users/jukiewiczm/followers,https://api.github.com/users/jukiewiczm/following{/other_user},https://api.github.com/users/jukiewiczm/gists{/gist_id},https://api.github.com/users/jukiewiczm/starred{/owner}{/repo},https://api.github.com/users/jukiewiczm/subscriptions,https://api.github.com/users/jukiewiczm/orgs,https://api.github.com/users/jukiewiczm/repos,https://api.github.com/users/jukiewiczm/events{/privacy},https://api.github.com/users/jukiewiczm/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46149/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46147,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46147/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46147/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46147/events,https://github.com/pandas-dev/pandas/issues/46147,1150218652,I_kwDOAA0YD85EjvGc,46147,ENH: Enumeration grouping,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk5NjA3NTg=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Discussion', 'name': 'Needs Discussion', 'color': '207de5', 'default': False, 'description': 'Requires discussion from core team before further action'}, {'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc2NDk3Nzc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info', 'name': 'Needs Info', 'color': '207de5', 'default': False, 'description': 'Clarification about behavior needed to assess issue'}]",open,False,,[],,3,2022-02-25T09:17:33Z,2022-02-27T16:15:52Z,,NONE,,"#### Is your feature request related to a problem?

I wish I could use pandas to do more general split-apply-combine workloads. The split-apply-combine pattern is supported today using [`groupby`](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html) and [windowing operations](https://pandas.pydata.org/pandas-docs/stable/user_guide/window.html). Whereas `groupby` is limited by the fact that every row in your DataFrame has to be mapped to 1-and-only-1 group, windowing operations are limited by having to have the same number of groups as rows in your DataFrame. This make both approaches unsuited for cases where you [want to compute summary statistics for a collection of arbitrary subsets of your data](https://stackoverflow.com/questions/71228107/vectorized-slice-aggregation-in-pandas).

Here are two examples of situations not covered today:
- Grouping a population dataset by age groups with overlap. Say, ages [0-9, 5-14, 10-19, 15-24, ...].
- Sliding windows with strides between windows > 1. Including non-constant strides.

#### Describe the solution you'd like

I came across a general solution that I really like in a language/tool called `esProc`. I haven't tried it in practice, and I know very little about the tool's merits, but reading the [documentation on what they call _enumeration grouping_](http://doc.raqsoft.com/esproc/tutorial/dwymjfz.html#_93), had me excited.

The idea is similar to `groupby`, but instead of specifying a column to group on, you provide a sequence of conditions, where each condition results in a group, that might or might not overlap other groups. This is pretty powerful, an results in a lot of flexibility.

Note that this solution doesn't really cover the sliding window ""stride inflexibility"" problem mentioned above, as you don't want to have to enumerate the masks that would give you your windows, but it does provide a more flexible alternative to `groupby`. I guess striding should be solved by enhancing the existing windowing APIs.

#### API breaking implications

N/A

#### Describe alternatives you've considered

- Add a column to the df, where each cell contains a list, enumerating the group memberships of its corresponding row. Then, using `df.explode` to create a df where `groupby` can be used as is. This is not satisfactory, as the `df.explode` call, as the method name suggests, risks being highly memory-inefficient, if there is a lot of group overlap.

- Concatenating the results of multiple group-bys. This is significantly more verbose and might result in arbitrarily many group-by cols.

#### Additional context

My original motivation for wanting this feature: https://stackoverflow.com/questions/71228107/vectorized-slice-aggregation-in-pandas

The `esProc` implementation (I think):
- https://github.com/SPLWare/esProc/blob/1d85ea8a758ecd8d8cec9c1531187871cc19a423/src/main/java/com/scudata/expression/mfn/sequence/Enum.java
- https://github.com/SPLWare/esProc/blob/5cd25c9eddbfef0b30628bcef3ef44aff1afee1e/src/main/java/com/scudata/dm/Sequence.java#L8613-L8743

How it could look in `pandas`:

```python

stats = df.enum_group(
    [df.age < 10, 5 <= df.age < 15, 10 <= df.age < 20, 15 <= df.age < 25]
).agg({""height"": ""mean""})


```
",https://api.github.com/repos/pandas-dev/pandas/issues/46147/timeline,,harahu,6145801,MDQ6VXNlcjYxNDU4MDE=,https://avatars.githubusercontent.com/u/6145801?v=4,,https://api.github.com/users/harahu,https://github.com/harahu,https://api.github.com/users/harahu/followers,https://api.github.com/users/harahu/following{/other_user},https://api.github.com/users/harahu/gists{/gist_id},https://api.github.com/users/harahu/starred{/owner}{/repo},https://api.github.com/users/harahu/subscriptions,https://api.github.com/users/harahu/orgs,https://api.github.com/users/harahu/repos,https://api.github.com/users/harahu/events{/privacy},https://api.github.com/users/harahu/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46147/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46144,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46144/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46144/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46144/events,https://github.com/pandas-dev/pandas/issues/46144,1150080362,I_kwDOAA0YD85EjNVq,46144,CI/TST: Flaky test `test_union_different_types`,"[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 48070600, 'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI', 'name': 'CI', 'color': 'a2bca7', 'default': False, 'description': 'Continuous Integration'}, {'id': 76939933, 'node_id': 'MDU6TGFiZWw3NjkzOTkzMw==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Unreliable%20Test', 'name': 'Unreliable Test', 'color': '5319e7', 'default': False, 'description': 'Unit tests that occasionally fail'}]",open,False,,[],,2,2022-02-25T06:08:12Z,2022-02-25T18:07:44Z,,MEMBER,,"Any idea @jbrockmendel why this may flaky with `Index[Int64]` and `Index[bool]`? 

e.g. https://github.com/pandas-dev/pandas/runs/5328797564?check_suite_focus=true

```
=================================== FAILURES ===================================
2022-02-25T04:50:41.4443922Z ________________ test_union_different_types[bool-dtype-repeats] ________________
2022-02-25T04:50:41.4448476Z [gw1] linux -- Python 3.8.12 /usr/share/miniconda/envs/pandas-dev/bin/python
2022-02-25T04:50:41.4448693Z 
2022-02-25T04:50:41.4449020Z index_flat = Index([True, True, True, True, True, True, True, True, False, False], dtype='bool')
2022-02-25T04:50:41.4449456Z index_flat2 = Int64Index([0, 0, 1, 1, 2, 2], dtype='int64')
2022-02-25T04:50:41.4449923Z request = <FixtureRequest for <Function test_union_different_types[bool-dtype-repeats]>>
2022-02-25T04:50:41.4450345Z 
2022-02-25T04:50:41.4450509Z     def test_union_different_types(index_flat, index_flat2, request):
2022-02-25T04:50:41.4450830Z         # This test only considers combinations of indices
2022-02-25T04:50:41.4451076Z         # GH 23525
2022-02-25T04:50:41.4451270Z         idx1 = index_flat
2022-02-25T04:50:41.4451485Z         idx2 = index_flat2
2022-02-25T04:50:41.4451684Z     
2022-02-25T04:50:41.4451866Z         if (
2022-02-25T04:50:41.4452059Z             not idx1.is_unique
2022-02-25T04:50:41.4452283Z             and not idx2.is_unique
2022-02-25T04:50:41.4452542Z             and not idx2.is_monotonic_decreasing
2022-02-25T04:50:41.4452784Z             and idx1.dtype.kind == ""i""
2022-02-25T04:50:41.4453032Z             and idx2.dtype.kind == ""b""
2022-02-25T04:50:41.4453250Z         ) or (
2022-02-25T04:50:41.4453436Z             not idx2.is_unique
2022-02-25T04:50:41.4453654Z             and not idx1.is_unique
2022-02-25T04:50:41.4453903Z             and not idx1.is_monotonic_decreasing
2022-02-25T04:50:41.4454143Z             and idx2.dtype.kind == ""i""
2022-02-25T04:50:41.4454381Z             and idx1.dtype.kind == ""b""
2022-02-25T04:50:41.4454590Z         ):
2022-02-25T04:50:41.4454812Z             mark = pytest.mark.xfail(
2022-02-25T04:50:41.4455086Z                 reason=""GH#44000 True==1"", raises=ValueError, strict=False
2022-02-25T04:50:41.4455335Z             )
2022-02-25T04:50:41.4455557Z             request.node.add_marker(mark)
2022-02-25T04:50:41.4455760Z     
2022-02-25T04:50:41.4456010Z         common_dtype = find_common_type([idx1.dtype, idx2.dtype])
2022-02-25T04:50:41.4456252Z     
2022-02-25T04:50:41.4456419Z         warn = None
2022-02-25T04:50:41.4456646Z         if not len(idx1) or not len(idx2):
2022-02-25T04:50:41.4457239Z             pass
2022-02-25T04:50:41.4457431Z         elif (
2022-02-25T04:50:41.4457646Z             idx1.dtype.kind == ""c""
2022-02-25T04:50:41.4457861Z             and (
2022-02-25T04:50:41.4458106Z                 idx2.dtype.kind not in [""i"", ""u"", ""f"", ""c""]
2022-02-25T04:50:41.4458377Z                 or not isinstance(idx2.dtype, np.dtype)
2022-02-25T04:50:41.4458612Z             )
2022-02-25T04:50:41.4458798Z         ) or (
2022-02-25T04:50:41.4458993Z             idx2.dtype.kind == ""c""
2022-02-25T04:50:41.4459206Z             and (
2022-02-25T04:50:41.4459448Z                 idx1.dtype.kind not in [""i"", ""u"", ""f"", ""c""]
2022-02-25T04:50:41.4459716Z                 or not isinstance(idx1.dtype, np.dtype)
2022-02-25T04:50:41.4459947Z             )
2022-02-25T04:50:41.4460129Z         ):
2022-02-25T04:50:41.4460451Z             # complex objects non-sortable
2022-02-25T04:50:41.4460697Z             warn = RuntimeWarning
2022-02-25T04:50:41.4460902Z     
2022-02-25T04:50:41.4461155Z         any_uint64 = idx1.dtype == np.uint64 or idx2.dtype == np.uint64
2022-02-25T04:50:41.4461571Z         idx1_signed = is_signed_integer_dtype(idx1.dtype)
2022-02-25T04:50:41.4461875Z         idx2_signed = is_signed_integer_dtype(idx2.dtype)
2022-02-25T04:50:41.4462107Z     
2022-02-25T04:50:41.4462434Z         # Union with a non-unique, non-monotonic index raises error
2022-02-25T04:50:41.4462730Z         # This applies to the boolean index
2022-02-25T04:50:41.4462973Z         idx1 = idx1.sort_values()
2022-02-25T04:50:41.4463185Z         idx2 = idx2.sort_values()
2022-02-25T04:50:41.4463385Z     
2022-02-25T04:50:41.4463741Z         with tm.assert_produces_warning(warn, match=""'<' not supported between""):
2022-02-25T04:50:41.4464034Z >           res1 = idx1.union(idx2)
2022-02-25T04:50:41.4464160Z 
2022-02-25T04:50:41.4464282Z pandas/tests/indexes/test_setops.py:99: 
2022-02-25T04:50:41.4464547Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2022-02-25T04:50:41.4464809Z pandas/core/indexes/base.py:3282: in union
2022-02-25T04:50:41.4465060Z     return left.union(right, sort=sort)
2022-02-25T04:50:41.4465332Z pandas/core/indexes/base.py:3292: in union
2022-02-25T04:50:41.4465591Z     result = self._union(other, sort=sort)
2022-02-25T04:50:41.4465853Z pandas/core/indexes/base.py:3342: in _union
2022-02-25T04:50:41.4466124Z     result = algos.union_with_duplicates(lvals, rvals)
2022-02-25T04:50:41.4466434Z pandas/core/algorithms.py:1850: in union_with_duplicates
2022-02-25T04:50:41.4466751Z     indexer += [i] * int(max(l_count.at[value], r_count.at[value]))
2022-02-25T04:50:41.4467026Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2022-02-25T04:50:41.4467172Z 
2022-02-25T04:50:41.4467264Z self = False    False
2022-02-25T04:50:41.4467464Z 0        False
2022-02-25T04:50:41.4467652Z dtype: bool
2022-02-25T04:50:41.4467758Z 
2022-02-25T04:50:41.4467832Z     @final
2022-02-25T04:50:41.4468031Z     def __nonzero__(self):
2022-02-25T04:50:41.4468251Z >       raise ValueError(
2022-02-25T04:50:41.4468513Z             f""The truth value of a {type(self).__name__} is ambiguous. ""
2022-02-25T04:50:41.4468820Z             ""Use a.empty, a.bool(), a.item(), a.any() or a.all().""
2022-02-25T04:50:41.4469054Z         )
2022-02-25T04:50:41.4469349Z E       ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
2022-02-25T04:50:41.4469577Z 
2022-02-25T04:50:41.4469689Z pandas/core/generic.py:1520: ValueError
2022-02-25T04:50:41.4470096Z ________________ test_union_different_types[repeats-bool-dtype] ________________
2022-02-25T04:50:41.4470542Z [gw1] linux -- Python 3.8.12 /usr/share/miniconda/envs/pandas-dev/bin/python
2022-02-25T04:50:41.4470741Z 
2022-02-25T04:50:41.4470932Z index_flat = Int64Index([0, 0, 1, 1, 2, 2], dtype='int64')
2022-02-25T04:50:41.4471375Z index_flat2 = Index([True, True, True, True, True, True, True, True, False, False], dtype='bool')
2022-02-25T04:50:41.4471953Z request = <FixtureRequest for <Function test_union_different_types[repeats-bool-dtype]>>
2022-02-25T04:50:41.4472187Z 
2022-02-25T04:50:41.4472342Z     def test_union_different_types(index_flat, index_flat2, request):
2022-02-25T04:50:41.4472646Z         # This test only considers combinations of indices
2022-02-25T04:50:41.4472886Z         # GH 23525
2022-02-25T04:50:41.4473090Z         idx1 = index_flat
2022-02-25T04:50:41.4473287Z         idx2 = index_flat2
2022-02-25T04:50:41.4473481Z     
2022-02-25T04:50:41.4473661Z         if (
2022-02-25T04:50:41.4473863Z             not idx1.is_unique
2022-02-25T04:50:41.4474073Z             and not idx2.is_unique
2022-02-25T04:50:41.4474328Z             and not idx2.is_monotonic_decreasing
2022-02-25T04:50:41.4474583Z             and idx1.dtype.kind == ""i""
2022-02-25T04:50:41.4474810Z             and idx2.dtype.kind == ""b""
2022-02-25T04:50:41.4475024Z         ) or (
2022-02-25T04:50:41.4475229Z             not idx2.is_unique
2022-02-25T04:50:41.4475435Z             and not idx1.is_unique
2022-02-25T04:50:41.4475795Z             and not idx1.is_monotonic_decreasing
2022-02-25T04:50:41.4476050Z             and idx2.dtype.kind == ""i""
2022-02-25T04:50:41.4476293Z             and idx1.dtype.kind == ""b""
2022-02-25T04:50:41.4476490Z         ):
2022-02-25T04:50:41.4476706Z             mark = pytest.mark.xfail(
2022-02-25T04:50:41.4477003Z                 reason=""GH#44000 True==1"", raises=ValueError, strict=False
2022-02-25T04:50:41.4477234Z             )
2022-02-25T04:50:41.4477461Z             request.node.add_marker(mark)
2022-02-25T04:50:41.4477679Z     
2022-02-25T04:50:41.4477919Z         common_dtype = find_common_type([idx1.dtype, idx2.dtype])
2022-02-25T04:50:41.4478167Z     
2022-02-25T04:50:41.4478355Z         warn = None
2022-02-25T04:50:41.4478569Z         if not len(idx1) or not len(idx2):
2022-02-25T04:50:41.4478787Z             pass
2022-02-25T04:50:41.4478977Z         elif (
2022-02-25T04:50:41.4479185Z             idx1.dtype.kind == ""c""
2022-02-25T04:50:41.4479382Z             and (
2022-02-25T04:50:41.4479628Z                 idx2.dtype.kind not in [""i"", ""u"", ""f"", ""c""]
2022-02-25T04:50:41.4479913Z                 or not isinstance(idx2.dtype, np.dtype)
2022-02-25T04:50:41.4480131Z             )
2022-02-25T04:50:41.4480318Z         ) or (
2022-02-25T04:50:41.4480526Z             idx2.dtype.kind == ""c""
2022-02-25T04:50:41.4480723Z             and (
2022-02-25T04:50:41.4480965Z                 idx1.dtype.kind not in [""i"", ""u"", ""f"", ""c""]
2022-02-25T04:50:41.4481248Z                 or not isinstance(idx1.dtype, np.dtype)
2022-02-25T04:50:41.4481463Z             )
2022-02-25T04:50:41.4481646Z         ):
2022-02-25T04:50:41.4481942Z             # complex objects non-sortable
2022-02-25T04:50:41.4482183Z             warn = RuntimeWarning
2022-02-25T04:50:41.4482370Z     
2022-02-25T04:50:41.4482623Z         any_uint64 = idx1.dtype == np.uint64 or idx2.dtype == np.uint64
2022-02-25T04:50:41.4482932Z         idx1_signed = is_signed_integer_dtype(idx1.dtype)
2022-02-25T04:50:41.4483220Z         idx2_signed = is_signed_integer_dtype(idx2.dtype)
2022-02-25T04:50:41.4483459Z     
2022-02-25T04:50:41.4483792Z         # Union with a non-unique, non-monotonic index raises error
2022-02-25T04:50:41.4484074Z         # This applies to the boolean index
2022-02-25T04:50:41.4484316Z         idx1 = idx1.sort_values()
2022-02-25T04:50:41.4484544Z         idx2 = idx2.sort_values()
2022-02-25T04:50:41.4484741Z     
2022-02-25T04:50:41.4485086Z         with tm.assert_produces_warning(warn, match=""'<' not supported between""):
2022-02-25T04:50:41.4485377Z >           res1 = idx1.union(idx2)
2022-02-25T04:50:41.4485515Z 
2022-02-25T04:50:41.4485634Z pandas/tests/indexes/test_setops.py:99: 
2022-02-25T04:50:41.4485884Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2022-02-25T04:50:41.4486144Z pandas/core/indexes/base.py:3282: in union
2022-02-25T04:50:41.4486403Z     return left.union(right, sort=sort)
2022-02-25T04:50:41.4486663Z pandas/core/indexes/base.py:3292: in union
2022-02-25T04:50:41.4486987Z     result = self._union(other, sort=sort)
2022-02-25T04:50:41.4487257Z pandas/core/indexes/base.py:3342: in _union
2022-02-25T04:50:41.4487541Z     result = algos.union_with_duplicates(lvals, rvals)
2022-02-25T04:50:41.4487840Z pandas/core/algorithms.py:1850: in union_with_duplicates
2022-02-25T04:50:41.4488152Z     indexer += [i] * int(max(l_count.at[value], r_count.at[value]))
2022-02-25T04:50:41.4488435Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2022-02-25T04:50:41.4488580Z 
2022-02-25T04:50:41.4488672Z self = 0        False
2022-02-25T04:50:41.4488867Z False    False
2022-02-25T04:50:41.4489082Z dtype: bool
2022-02-25T04:50:41.4489210Z 
2022-02-25T04:50:41.4489290Z     @final
2022-02-25T04:50:41.4489482Z     def __nonzero__(self):
2022-02-25T04:50:41.4489715Z >       raise ValueError(
2022-02-25T04:50:41.4490003Z             f""The truth value of a {type(self).__name__} is ambiguous. ""
2022-02-25T04:50:41.4490429Z             ""Use a.empty, a.bool(), a.item(), a.any() or a.all().""
2022-02-25T04:50:41.4490774Z         )
2022-02-25T04:50:41.4491100Z E       ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```",https://api.github.com/repos/pandas-dev/pandas/issues/46144/timeline,,mroeschke,10647082,MDQ6VXNlcjEwNjQ3MDgy,https://avatars.githubusercontent.com/u/10647082?v=4,,https://api.github.com/users/mroeschke,https://github.com/mroeschke,https://api.github.com/users/mroeschke/followers,https://api.github.com/users/mroeschke/following{/other_user},https://api.github.com/users/mroeschke/gists{/gist_id},https://api.github.com/users/mroeschke/starred{/owner}{/repo},https://api.github.com/users/mroeschke/subscriptions,https://api.github.com/users/mroeschke/orgs,https://api.github.com/users/mroeschke/repos,https://api.github.com/users/mroeschke/events{/privacy},https://api.github.com/users/mroeschke/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46144/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46141,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46141/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46141/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46141/events,https://github.com/pandas-dev/pandas/pull/46141,1149585395,PR_kwDOAA0YD84za7en,46141,[WIP] DataFrame exchange protocol,"[{'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2NTEwNg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Compat', 'name': 'Compat', 'color': '0052cc', 'default': False, 'description': 'pandas objects compatability with Numpy or Python functions'}]",open,False,,[],,2,2022-02-24T18:01:38Z,2022-02-27T01:16:13Z,,CONTRIBUTOR,,"Do note that this PR is currently work-in-progress, mostly to facilitate the discussion on how the implementation should be going.

It also vendors the [exchange spec](https://github.com/data-apis/dataframe-api/pull/74) and [exchange tests](https://github.com/data-apis/dataframe-api/pull/75), which aren't yet merged at the consortium, so I'll keep updating the vendored copies as the discussion goes there.

More tests are also to be added, as well as the implementations of some cases (a lot of non-central cases are `NotImplemented` now, as I've built this upon [the prototype](https://github.com/data-apis/dataframe-api/blob/main/protocol/pandas_implementation.py).

- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",https://api.github.com/repos/pandas-dev/pandas/issues/46141/timeline,,vnlitvinov,45396231,MDQ6VXNlcjQ1Mzk2MjMx,https://avatars.githubusercontent.com/u/45396231?v=4,,https://api.github.com/users/vnlitvinov,https://github.com/vnlitvinov,https://api.github.com/users/vnlitvinov/followers,https://api.github.com/users/vnlitvinov/following{/other_user},https://api.github.com/users/vnlitvinov/gists{/gist_id},https://api.github.com/users/vnlitvinov/starred{/owner}{/repo},https://api.github.com/users/vnlitvinov/subscriptions,https://api.github.com/users/vnlitvinov/orgs,https://api.github.com/users/vnlitvinov/repos,https://api.github.com/users/vnlitvinov/events{/privacy},https://api.github.com/users/vnlitvinov/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46141/reactions,0,0,0,0,0,0,0,0,0,True,https://api.github.com/repos/pandas-dev/pandas/pulls/46141,https://github.com/pandas-dev/pandas/pull/46141,https://github.com/pandas-dev/pandas/pull/46141.diff,https://github.com/pandas-dev/pandas/pull/46141.patch,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46140,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46140/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46140/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46140/events,https://github.com/pandas-dev/pandas/pull/46140,1149320791,PR_kwDOAA0YD84zaDbX,46140,Bug fix - extension array with 2d datetime64,"[{'id': 13101118, 'node_id': 'MDU6TGFiZWwxMzEwMTExOA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Output-Formatting', 'name': 'Output-Formatting', 'color': 'ededed', 'default': False, 'description': '__repr__ of pandas objects, to_string'}, {'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDkwMjM2OTM=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ExtensionArray', 'name': 'ExtensionArray', 'color': '6138b5', 'default': False, 'description': 'Extending pandas with custom dtypes or arrays.'}]",open,False,,[],,1,2022-02-24T13:57:11Z,2022-02-27T22:59:38Z,,CONTRIBUTOR,,"- [x] closes #38390
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",https://api.github.com/repos/pandas-dev/pandas/issues/46140/timeline,,weikhor,36619387,MDQ6VXNlcjM2NjE5Mzg3,https://avatars.githubusercontent.com/u/36619387?v=4,,https://api.github.com/users/weikhor,https://github.com/weikhor,https://api.github.com/users/weikhor/followers,https://api.github.com/users/weikhor/following{/other_user},https://api.github.com/users/weikhor/gists{/gist_id},https://api.github.com/users/weikhor/starred{/owner}{/repo},https://api.github.com/users/weikhor/subscriptions,https://api.github.com/users/weikhor/orgs,https://api.github.com/users/weikhor/repos,https://api.github.com/users/weikhor/events{/privacy},https://api.github.com/users/weikhor/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46140/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46140,https://github.com/pandas-dev/pandas/pull/46140,https://github.com/pandas-dev/pandas/pull/46140.diff,https://github.com/pandas-dev/pandas/pull/46140.patch,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46138,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46138/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46138/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46138/events,https://github.com/pandas-dev/pandas/issues/46138,1149229930,I_kwDOAA0YD85Ef9tq,46138,BUG: NotImplementedError: Cannot apply ufunc <ufunc 'hyp2f1'> to mixed DataFrame and Series inputs.,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc2NDk3Nzc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info', 'name': 'Needs Info', 'color': '207de5', 'default': False, 'description': 'Clarification about behavior needed to assess issue'}]",open,False,,[],,3,2022-02-24T12:29:14Z,2022-02-24T16:28:56Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
#imports
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
import pandas as pd
import numpy as np
from datetime import datetime
!pip install lifetimes
from lifetimes import ParetoNBDFitter, GammaGammaFitter

#data
f_and_t = drive.CreateFile({'id': '1sXcv0SUUygyFvjVEtdV3kk8zyjp4GGQC'})
f_and_t.GetContentFile('f_and_t.csv')
f_and_t = pd.read_csv('f_and_t.csv')
```
#reproducable example
```
time_days = 126
time_months = int(math.ceil(time_days / 30.0))   

#column-selection

summary = f_and_t[['customer_id', 'frequency_btyd', 'recency', 'T',
                 'monetary_btyd']]
                 
summary.columns = ['customer_id', 'frequency', 'recency', 'T',
                     'monetary_value']
summary = summary.set_index('customer_id')

actual_df = f_and_t[['customer_id', 'frequency_btyd', 'monetary_dnn',
                     'target_monetary']]
actual_df.columns = ['customer_id', 'train_frequency', 'train_monetary',
                       'act_target_monetary']

#PARETO/NBD fitter
paretof = ParetoNBDFitter(penalizer_coef= 0.01)
paretof.fit(summary['frequency'], summary['recency'], summary['T'])

#Gamma Gamma Fitter

ggf = GammaGammaFitter(penalizer_coef=0)
ggf.fit(summary['frequency'], summary['monetary_value'])

#pareto predict

pareto_pred = paretof.predict(time_days,
                               summary['frequency'].values,
                                summary['recency'],
                                 summary['T'])

trans_pred = pareto_pred.fillna(0)

#gg predict

predicted_value = ggf.customer_lifetime_value(paretof,
                                                summary['frequency'],#.values,
                                                summary['recency'],
                                                summary['T'],
                                                summary['monetary_value'],
                                                time=time_months,
                                                discount_rate= 0.01)
```
```


### Issue Description

I was using the lifetimes library to calculate CLV for a list of customers. From one day to an other this issue appeared. I work on Google Colab with Pandas 1.3.5 (their current version). The error below appears for both functions: paretof.predict and ggf.customer_lifetime_value. For paretof.

I already found posts to this issue, from half a  year ago (https://stackoverflow.com/questions/69071130/lifetimes-library-issue-of-calculating-clv-when-using-function-customer-lifet).  The solution to use "".values"" only worked for the paretof.predict function. At the ggf.customer_lifetime_value function I am stuck. 

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-119-dcf79bdac207>](https://rvlrb8qepl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220222-060103-RC01_430258751#) in <module>()
     58                                                 summary['monetary_value'],
     59                                                 time=time_months,
---> 60                                                 discount_rate=discount_rate)
     61 
     62 

6 frames
[/usr/local/lib/python3.7/dist-packages/lifetimes/fitters/gamma_gamma_fitter.py](https://rvlrb8qepl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220222-060103-RC01_430258751#) in customer_lifetime_value(self, transaction_prediction_model, frequency, recency, T, monetary_value, time, discount_rate, freq)
    294 
    295         return _customer_lifetime_value(
--> 296             transaction_prediction_model, frequency, recency, T, adjusted_monetary_value, time, discount_rate, freq=freq
    297         )

[/usr/local/lib/python3.7/dist-packages/lifetimes/utils.py](https://rvlrb8qepl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220222-060103-RC01_430258751#) in _customer_lifetime_value(transaction_prediction_model, frequency, recency, T, monetary_value, time, discount_rate, freq)
    496         # since the prediction of number of transactions is cumulative, we have to subtract off the previous periods
    497         expected_number_of_transactions = transaction_prediction_model.predict(
--> 498             i, frequency, recency, T
    499         ) - transaction_prediction_model.predict(i - factor, frequency, recency, T)
    500         # sum up the CLV estimates of all of the periods and apply discounted cash flow

[/usr/local/lib/python3.7/dist-packages/lifetimes/fitters/pareto_nbd_fitter.py](https://rvlrb8qepl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220222-060103-RC01_430258751#) in conditional_expected_number_of_purchases_up_to_time(self, t, frequency, recency, T)
    277         r, alpha, s, beta = params
    278 
--> 279         likelihood = self._conditional_log_likelihood(params, x, t_x, T)
    280         first_term = (
    281             gammaln(r + x) - gammaln(r) + r * log(alpha) + s * log(beta) - (r + x) * log(alpha + T) - s * log(beta + T)

[/usr/local/lib/python3.7/dist-packages/lifetimes/fitters/pareto_nbd_fitter.py](https://rvlrb8qepl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220222-060103-RC01_430258751#) in _conditional_log_likelihood(params, freq, rec, T)
    212 
    213         A_1 = gammaln(r + x) - gammaln(r) + r * log(alpha) + s * log(beta)
--> 214         log_A_0 = ParetoNBDFitter._log_A_0(params, x, rec, T)
    215 
    216         A_2 = logaddexp(-(r + x) * log(alpha + T) - s * log(beta + T), log(s) + log_A_0 - log(r_s_x))

[/usr/local/lib/python3.7/dist-packages/lifetimes/fitters/pareto_nbd_fitter.py](https://rvlrb8qepl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220222-060103-RC01_430258751#) in _log_A_0(params, freq, recency, age)
    179 
    180         rsf = r + s + freq
--> 181         p_1 = hyp2f1(rsf, t, rsf + 1.0, abs_alpha_beta / (max_of_alpha_beta + recency))
    182         q_1 = max_of_alpha_beta + recency
    183         p_2 = hyp2f1(rsf, t, rsf + 1.0, abs_alpha_beta / (max_of_alpha_beta + age))

[/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py](https://rvlrb8qepl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220222-060103-RC01_430258751#) in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
   2030         self, ufunc: np.ufunc, method: str, *inputs: Any, **kwargs: Any
   2031     ):
-> 2032         return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
   2033 
   2034     # ideally we would define this to avoid the getattr checks, but

[/usr/local/lib/python3.7/dist-packages/pandas/core/arraylike.py](https://rvlrb8qepl-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220222-060103-RC01_430258751#) in array_ufunc(self, ufunc, method, *inputs, **kwargs)
    292             raise NotImplementedError(
    293                 ""Cannot apply ufunc {} to mixed DataFrame and Series ""
--> 294                 ""inputs."".format(ufunc)
    295             )
    296         axes = self.axes

NotImplementedError: Cannot apply ufunc <ufunc 'hyp2f1'> to mixed DataFrame and Series inputs.
```



### Expected Behavior

Sometimes it works, but mostly it doesnt anymore. It should just no Error appear...

### Installed Versions

<details>

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning:

The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use ""pip install psycopg2-binary"" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.


INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.7.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.144+
Version          : #1 SMP Tue Dec 7 09:58:10 PST 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.5
numpy            : 1.21.5
pytz             : 2018.9
dateutil         : 2.8.2
pip              : 21.1.3
setuptools       : 57.4.0
Cython           : 0.29.28
pytest           : 3.6.4
hypothesis       : None
sphinx           : 1.8.6
blosc            : None
feather          : 0.4.1
xlsxwriter       : None
lxml.etree       : 4.2.6
html5lib         : 1.0.1
pymysql          : None
psycopg2         : 2.7.6.1 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 5.5.0
pandas_datareader: 0.9.0
bs4              : 4.6.3
bottleneck       : 1.3.2
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.2
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : 0.13.3
pyarrow          : 6.0.1
pyxlsb           : None
s3fs             : None
scipy            : 1.4.1
sqlalchemy       : 1.4.31
tables           : 3.7.0
tabulate         : 0.8.9
xarray           : 0.18.2
xlrd             : 1.1.0
xlwt             : 1.3.0
numba            : 0.51.2

</details>
",https://api.github.com/repos/pandas-dev/pandas/issues/46138/timeline,,timmy-ops,89028359,MDQ6VXNlcjg5MDI4MzU5,https://avatars.githubusercontent.com/u/89028359?v=4,,https://api.github.com/users/timmy-ops,https://github.com/timmy-ops,https://api.github.com/users/timmy-ops/followers,https://api.github.com/users/timmy-ops/following{/other_user},https://api.github.com/users/timmy-ops/gists{/gist_id},https://api.github.com/users/timmy-ops/starred{/owner}{/repo},https://api.github.com/users/timmy-ops/subscriptions,https://api.github.com/users/timmy-ops/orgs,https://api.github.com/users/timmy-ops/repos,https://api.github.com/users/timmy-ops/events{/privacy},https://api.github.com/users/timmy-ops/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46138/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46135,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46135/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46135/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46135/events,https://github.com/pandas-dev/pandas/issues/46135,1148668016,I_kwDOAA0YD85Ed0hw,46135,"BUG: rolling with axis=1, win_type=, and center=True raises ValueError","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1045950827, 'node_id': 'MDU6TGFiZWwxMDQ1OTUwODI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Window', 'name': 'Window', 'color': 'd4c5f9', 'default': False, 'description': 'rolling, ewma, expanding'}]",open,False,,[],,0,2022-02-23T23:00:08Z,2022-02-24T00:04:41Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame([[0]])
# this works:
print(df.rolling(window=1, axis=0, win_type=""boxcar"", center=True).sum())
# This raises ValueError:
print(df.rolling(window=1, axis=1, win_type=""boxcar"", center=True).sum())
```


### Issue Description

I start with a dataframe with a single value, 0. Rolling over columns with the above parameters gives:

```
     0
0  3.0
```

Rolling over rows with `axis=1` instead gives `ValueError: Requested axis is larger then no. of argument dimensions`:

<details>

<summary>Show stack trace</summary>

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [48], in <module>
----> 1 df.rolling(window=1, axis=1, win_type=""boxcar"", center=True).sum()

File /usr/local/lib/python3.9/site-packages/pandas/core/window/rolling.py:1216, in Window.sum(self, *args, **kwargs)
   1212 window_func = window_aggregations.roll_weighted_sum
   1213 # error: Argument 1 to ""_apply"" of ""Window"" has incompatible type
   1214 # ""Callable[[ndarray, ndarray, int], ndarray]""; expected
   1215 # ""Callable[[ndarray, int, int], ndarray]""
-> 1216 return self._apply(window_func, name=""sum"", **kwargs)

File /usr/local/lib/python3.9/site-packages/pandas/core/window/rolling.py:1154, in Window._apply(self, func, name, numba_cache_key, numba_args, **kwargs)
   1150         result = self._center_window(result, offset)
   1152     return result
-> 1154 return self._apply_blockwise(homogeneous_func, name)

File /usr/local/lib/python3.9/site-packages/pandas/core/window/rolling.py:462, in BaseWindow._apply_blockwise(self, homogeneous_func, name)
    459 for i, arr in enumerate(obj._iter_column_arrays()):
    460     # GH#42736 operate column-wise instead of block-wise
    461     try:
--> 462         res = hfunc(arr)
    463     except (TypeError, NotImplementedError):
    464         pass

File /usr/local/lib/python3.9/site-packages/pandas/core/window/rolling.py:452, in BaseWindow._apply_blockwise.<locals>.hfunc(values)
    450 def hfunc(values: ArrayLike) -> ArrayLike:
    451     values = self._prep_values(values)
--> 452     return homogeneous_func(values)

File /usr/local/lib/python3.9/site-packages/pandas/core/window/rolling.py:1150, in Window._apply.<locals>.homogeneous_func(values)
   1147     result = np.asarray(calc(values))
   1149 if self.center:
-> 1150     result = self._center_window(result, offset)
   1152 return result

File /usr/local/lib/python3.9/site-packages/pandas/core/window/rolling.py:1092, in Window._center_window(self, result, offset)
   1088 """"""
   1089 Center the result in the window for weighted rolling aggregations.
   1090 """"""
   1091 if self.axis > result.ndim - 1:
-> 1092     raise ValueError(""Requested axis is larger then no. of argument dimensions"")
   1094 if offset > 0:
   1095     lead_indexer = [slice(None)] * result.ndim

ValueError: Requested axis is larger then no. of argument dimensions
```
</details>

### Expected Behavior

I expect rolling over axis 1 to give the same result as rolling over axis 0 for this single-element dataframe.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : b4e578db857f0705144a56eac0ab65d6fb0a8760
python           : 3.9.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.3.0
Version          : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+122.gb4e578db85
numpy            : 1.22.1
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 60.8.2
Cython           : 0.29.27
pytest           : 7.0.0
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.0.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : 2022.01.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : 0.16.0
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.01.0
scipy            : 1.7.3
sqlalchemy       : 1.4.31
tables           : 3.7.0
tabulate         : None
xarray           : 0.20.2
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>
",https://api.github.com/repos/pandas-dev/pandas/issues/46135/timeline,,mvashishtha,10712109,MDQ6VXNlcjEwNzEyMTA5,https://avatars.githubusercontent.com/u/10712109?v=4,,https://api.github.com/users/mvashishtha,https://github.com/mvashishtha,https://api.github.com/users/mvashishtha/followers,https://api.github.com/users/mvashishtha/following{/other_user},https://api.github.com/users/mvashishtha/gists{/gist_id},https://api.github.com/users/mvashishtha/starred{/owner}{/repo},https://api.github.com/users/mvashishtha/subscriptions,https://api.github.com/users/mvashishtha/orgs,https://api.github.com/users/mvashishtha/repos,https://api.github.com/users/mvashishtha/events{/privacy},https://api.github.com/users/mvashishtha/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46135/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46132,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46132/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46132/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46132/events,https://github.com/pandas-dev/pandas/issues/46132,1148620065,I_kwDOAA0YD85Edo0h,46132,BUG: rolling aggregate() with a list of functions along axis 1 raises ValueError,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc3OTIwNjc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Apply', 'name': 'Apply', 'color': 'fbca04', 'default': False, 'description': 'Apply, Aggregate, Transform'}, {'id': 1045950827, 'node_id': 'MDU6TGFiZWwxMDQ1OTUwODI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Window', 'name': 'Window', 'color': 'd4c5f9', 'default': False, 'description': 'rolling, ewma, expanding'}]",open,False,,[],,0,2022-02-23T21:54:33Z,2022-02-24T21:21:29Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
import numpy as np

df = pd.DataFrame([[1, 2], [3, 4]])
# rolling across axis=0 works fine:
print(df.rolling(window=2, axis=0, min_periods=1).aggregate([np.sum, np.mean]))
# This causes a ValueError
print(df.rolling(window=2, axis=1, min_periods=1).aggregate([np.sum, np.mean]))
```


### Issue Description

I start with the dataframe:

```
   0  1
0  1  2
1  3  4
```

Rolling over `axis=0` gives the rolling sum and mean for each column:

```
     0         1
   sum mean  sum mean
0  1.0  1.0  2.0  2.0
1  4.0  2.0  6.0  3.0
```

Rolling over `axis=1` should give rolling sum and mean for each row, but instead raises a `ValueError: No axis named 1 for object type Series`:

<details>
<summary>Show stack trace</summary>

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/pandas/pandas/core/generic.py:535, in NDFrame._get_axis_number(cls, axis)
    534 try:
--> 535     return cls._AXIS_TO_AXIS_NUMBER[axis]
    536 except KeyError:

KeyError: 1

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Input In [20], in <module>
      4 df = pd.DataFrame([[1, 2], [3, 4]])
      5 # rolling across axis=0 works fine:
----> 6 df.rolling(window=2, axis=1, min_periods=1).aggregate([np.sum, np.mean])

File ~/pandas/pandas/core/window/rolling.py:1765, in Rolling.aggregate(self, func, *args, **kwargs)
   1727 @doc(
   1728     _shared_docs[""aggregate""],
   1729     see_also=dedent(
   (...)
   1763 )
   1764 def aggregate(self, func, *args, **kwargs):
-> 1765     return super().aggregate(func, *args, **kwargs)

File ~/pandas/pandas/core/window/rolling.py:635, in BaseWindow.aggregate(self, func, *args, **kwargs)
    634 def aggregate(self, func, *args, **kwargs):
--> 635     result = ResamplerWindowApply(self, func, args=args, kwargs=kwargs).agg()
    636     if result is None:
    637         return self.apply(func, raw=False, args=args, kwargs=kwargs)

File ~/pandas/pandas/core/apply.py:171, in Apply.agg(self)
    168     return self.agg_dict_like()
    169 elif is_list_like(arg):
    170     # we require a list, but not a 'str'
--> 171     return self.agg_list_like()
    173 if callable(arg):
    174     f = com.get_cython_func(arg)

File ~/pandas/pandas/core/apply.py:367, in Apply.agg_list_like(self)
    365 indices = []
    366 for index, col in enumerate(selected_obj):
--> 367     colg = obj._gotitem(col, ndim=1, subset=selected_obj.iloc[:, index])
    368     try:
    369         # Capture and suppress any warnings emitted by us in the call
    370         # to agg below, but pass through any warnings that were
    371         # generated otherwise.
    372         # This is necessary because of https://bugs.python.org/issue29672
    373         # See GH #43741 for more details
    374         with warnings.catch_warnings(record=True) as record:

File ~/pandas/pandas/core/window/rolling.py:289, in BaseWindow._gotitem(self, key, ndim, subset)
    284 if subset.ndim == 2 and (
    285     (is_scalar(key) and key in subset) or is_list_like(key)
    286 ):
    287     selection = key
--> 289 new_win = type(self)(subset, selection=selection, **kwargs)
    290 return new_win

File ~/pandas/pandas/core/window/rolling.py:141, in BaseWindow.__init__(self, obj, window, min_periods, center, win_type, axis, on, closed, method, selection)
    139 # TODO(2.0): Change this back to self.win_type once deprecation is enforced
    140 self._win_type = win_type
--> 141 self.axis = obj._get_axis_number(axis) if axis is not None else None
    142 self.method = method
    143 self._win_freq_i8 = None

File ~/pandas/pandas/core/generic.py:537, in NDFrame._get_axis_number(cls, axis)
    535     return cls._AXIS_TO_AXIS_NUMBER[axis]
    536 except KeyError:
--> 537     raise ValueError(f""No axis named {axis} for object type {cls.__name__}"")

ValueError: No axis named 1 for object type Series
```
</details>

### Expected Behavior

I expect the last `rolling` call to give a dataframe with the rolling sums and means of each row:

```
          0    1
0 sum   1.0  3.0
  mean  1.0  1.5
1 sum   3.0  7.0
  mean  3.0  3.5

```




### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : b4e578db857f0705144a56eac0ab65d6fb0a8760
python           : 3.9.10.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.3.0
Version          : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.0.dev0+122.gb4e578db85
numpy            : 1.22.1
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 22.0.3
setuptools       : 60.8.2
Cython           : 0.29.27
pytest           : 7.0.0
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.0.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : 2022.01.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : 0.16.0
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : 2022.01.0
scipy            : 1.7.3
sqlalchemy       : 1.4.31
tables           : 3.7.0
tabulate         : None
xarray           : 0.20.2
xlrd             : 2.0.1
xlwt             : None
zstandard        : None

</details>
",https://api.github.com/repos/pandas-dev/pandas/issues/46132/timeline,,mvashishtha,10712109,MDQ6VXNlcjEwNzEyMTA5,https://avatars.githubusercontent.com/u/10712109?v=4,,https://api.github.com/users/mvashishtha,https://github.com/mvashishtha,https://api.github.com/users/mvashishtha/followers,https://api.github.com/users/mvashishtha/following{/other_user},https://api.github.com/users/mvashishtha/gists{/gist_id},https://api.github.com/users/mvashishtha/starred{/owner}{/repo},https://api.github.com/users/mvashishtha/subscriptions,https://api.github.com/users/mvashishtha/orgs,https://api.github.com/users/mvashishtha/repos,https://api.github.com/users/mvashishtha/events{/privacy},https://api.github.com/users/mvashishtha/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46132/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46129,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46129/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46129/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46129/events,https://github.com/pandas-dev/pandas/issues/46129,1148107383,I_kwDOAA0YD85Ebrp3,46129,BUG: df.plot(kind='barh') does not show xlabel,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,1,2022-02-23T13:37:44Z,2022-02-24T07:18:05Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
import matplotlib.pyplot as plt

co2 = pd.Series({
    'train': 4.8,
    'car': 128.5,
    'aiplane': 98.5
})

co2.plot(
    kind='barh',
    title='CO₂ Tübingen to Berlin',
    xlabel='kg CO₂-eq'
)

plt.show()
```


### Issue Description

The code produces the following plot, with the xlabel showing up on the y-axis.
![image](https://user-images.githubusercontent.com/36071676/155328546-eb9915a2-af5b-4346-a705-5eaf96e2851a.png)

When only supplying the ylabel, everything works as expected.
When supplying both, the xlabel overrides the ylabel

### Expected Behavior

The xlabel should show up on the x-axis.

### Installed Versions

<details>


INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.13.0-30-generic
Version          : #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.22.0
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 22.0.3
setuptools       : 58.1.0
Cython           : 0.29.21
pytest           : 6.2.5
hypothesis       : None
sphinx           : 3.4.3
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.2
html5lib         : None
pymysql          : None
psycopg2         : 2.8.6
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : 0.8.4
gcsfs            : None
matplotlib       : 3.5.1
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : 6.0.1
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
sqlalchemy       : 1.3.24
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None


</details>
",https://api.github.com/repos/pandas-dev/pandas/issues/46129/timeline,,McToel,36071676,MDQ6VXNlcjM2MDcxNjc2,https://avatars.githubusercontent.com/u/36071676?v=4,,https://api.github.com/users/McToel,https://github.com/McToel,https://api.github.com/users/McToel/followers,https://api.github.com/users/McToel/following{/other_user},https://api.github.com/users/McToel/gists{/gist_id},https://api.github.com/users/McToel/starred{/owner}{/repo},https://api.github.com/users/McToel/subscriptions,https://api.github.com/users/McToel/orgs,https://api.github.com/users/McToel/repos,https://api.github.com/users/McToel/events{/privacy},https://api.github.com/users/McToel/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46129/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46126,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46126/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46126/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46126/events,https://github.com/pandas-dev/pandas/issues/46126,1147900564,I_kwDOAA0YD85Ea5KU,46126,ENH: Conversion function errors kwarg callback function,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,3,2022-02-23T10:17:17Z,2022-02-24T01:12:05Z,,NONE,,"#### Is your feature request related to a problem?

I'm trying to ingest a large amount of data from a csv file into postgres. However, the types in the csv do not perfectly match those of the DB schema, so I load the file in a dataframe for dtype conversion.

`.astype` functions currently only allow `errors={'raise', 'ignore'}`, meaning conversion either fails or doesn't happen - both resulting in not being able to ingest the data. 

#### Describe the solution you'd like

A callback for the `errors` kwarg would be very useful here - accepting a function to apply to the failed element to do a valid conversion.

For example:
```python
x = pd.Series([100, 10, 1, ""bad""])
x.astype(""Int32"") # fails
x.astype(""Int32"", errors=""ignore"") # does nothing because of the bad row
# callback to replicate ""coerce"" behaviour
x.astype(""Int32"", errors=lambda x: np.nan)
```

Another, more involved case:
```python
x = pd.Series([1000000000, 10, 12, -10000000000])
x.astype(""Int32"") # fails

# hypothetical case where positive out-of-range values are truncated and other errors are NA
def int32_conv_callback(x):
    if isinstance(x, numbers.Number) and (x > 2**31):
        return np.int32(2 ** 32)
    else:
        return pd.NA

x.astype(""Int32"", errors=int32_conv_callback)
# (2**31, 10, 12, <NA>)
```

#### API breaking implications

None, an option is added, backwards compatibility is maintained.

#### Describe alternatives you've considered

Adding the `'coerce'` option to `.astype`, which would fill the appropriate null type on failure. NaNs are better than not being able to use a dataframe (and probably cover most cases).
",https://api.github.com/repos/pandas-dev/pandas/issues/46126/timeline,,timlod,7346303,MDQ6VXNlcjczNDYzMDM=,https://avatars.githubusercontent.com/u/7346303?v=4,,https://api.github.com/users/timlod,https://github.com/timlod,https://api.github.com/users/timlod/followers,https://api.github.com/users/timlod/following{/other_user},https://api.github.com/users/timlod/gists{/gist_id},https://api.github.com/users/timlod/starred{/owner}{/repo},https://api.github.com/users/timlod/subscriptions,https://api.github.com/users/timlod/orgs,https://api.github.com/users/timlod/repos,https://api.github.com/users/timlod/events{/privacy},https://api.github.com/users/timlod/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46126/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46122,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46122/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46122/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46122/events,https://github.com/pandas-dev/pandas/issues/46122,1147506497,I_kwDOAA0YD85EZY9B,46122,ENH: Add option to specify table captions to be below tables in DataFrame.to_latex,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 251382258, 'node_id': 'MDU6TGFiZWwyNTEzODIyNTg=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20LaTeX', 'name': 'IO LaTeX', 'color': '006b75', 'default': False, 'description': 'to_latex'}, {'id': 1728592794, 'node_id': 'MDU6TGFiZWwxNzI4NTkyNzk0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Styler', 'name': 'Styler', 'color': '006b75', 'default': False, 'description': 'conditional formatting using DataFrame.style'}]",open,False,,[],,1,2022-02-23T00:35:15Z,2022-02-23T19:22:01Z,,NONE,,"#### Is your feature request related to a problem?

At present, table captions are always written above the table in the outputs. LaTeX will then render the caption above the table in the resulting document.

I prefer to put captions below tables (and figures) and would like the option to do so added to `DataFrame.to_latex`.


#### Describe the solution you'd like

I propose adding a new argument to `DataFrame.to_latex`, (say _caption\_position_) with a default of `'above'`and valid values of `'above'` and `'below'`. One could equivalently use an Enum, but I'm not sure where that would live and don't think this idiomatic w.r.t. Pandas. 

An alternative would be an argument _caption\_above_ with valid values of `True` and `False`.

I think the docstring would be something like

```Python
""""""
Parameters
----------
caption_position : str, default 'above'
    Position of the caption relative to the table. Acceptable values are `'above'` and `'below'`.
""""""
``` 


#### API breaking implications

With a default, this should not change the API.


#### Describe alternatives you've considered

At present, I wait until I finally want to submit the document then manually change the files (where I put the output of `DataFrame.to_latex`) manually. Without this feature, I would consider writing a function that takes the output of `DataFrame.to_latex` and rearranges it.

#### Note

I'm happy to have a go at this — if it is not so trivial that someone can do it faster than saying _OK_ — if people are happy with the proposed approach.",https://api.github.com/repos/pandas-dev/pandas/issues/46122/timeline,,Sleepingwell,294943,MDQ6VXNlcjI5NDk0Mw==,https://avatars.githubusercontent.com/u/294943?v=4,,https://api.github.com/users/Sleepingwell,https://github.com/Sleepingwell,https://api.github.com/users/Sleepingwell/followers,https://api.github.com/users/Sleepingwell/following{/other_user},https://api.github.com/users/Sleepingwell/gists{/gist_id},https://api.github.com/users/Sleepingwell/starred{/owner}{/repo},https://api.github.com/users/Sleepingwell/subscriptions,https://api.github.com/users/Sleepingwell/orgs,https://api.github.com/users/Sleepingwell/repos,https://api.github.com/users/Sleepingwell/events{/privacy},https://api.github.com/users/Sleepingwell/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46122/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46116,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46116/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46116/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46116/events,https://github.com/pandas-dev/pandas/pull/46116,1147166642,PR_kwDOAA0YD84zTHun,46116,[WIP] perf improvements for strftime,"[{'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4NDA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timeseries', 'name': 'Timeseries', 'color': 'AFEEEE', 'default': False, 'description': None}, {'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance', 'name': 'Performance', 'color': 'a10c02', 'default': False, 'description': 'Memory or execution speed performance'}]",open,False,,[],,5,2022-02-22T17:12:49Z,2022-02-27T01:19:30Z,,CONTRIBUTOR,,"Changelog

 - Added the default format ""%Y-%m-%d %H:%M:%S"" as basic format (same as format=None), as suggested by @auderson.

- [ ] closes #44764
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
- [ ] Post `timeit` results showing the perf improvements",https://api.github.com/repos/pandas-dev/pandas/issues/46116/timeline,,smarie,3236794,MDQ6VXNlcjMyMzY3OTQ=,https://avatars.githubusercontent.com/u/3236794?v=4,,https://api.github.com/users/smarie,https://github.com/smarie,https://api.github.com/users/smarie/followers,https://api.github.com/users/smarie/following{/other_user},https://api.github.com/users/smarie/gists{/gist_id},https://api.github.com/users/smarie/starred{/owner}{/repo},https://api.github.com/users/smarie/subscriptions,https://api.github.com/users/smarie/orgs,https://api.github.com/users/smarie/repos,https://api.github.com/users/smarie/events{/privacy},https://api.github.com/users/smarie/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46116/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46116,https://github.com/pandas-dev/pandas/pull/46116,https://github.com/pandas-dev/pandas/pull/46116.diff,https://github.com/pandas-dev/pandas/pull/46116.patch,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46114,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46114/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46114/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46114/events,https://github.com/pandas-dev/pandas/pull/46114,1146960626,PR_kwDOAA0YD84zScJh,46114,DOC: Add note for tail/head when n is larger then length of DataFrame,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}]",open,False,,[],,1,2022-02-22T14:10:00Z,2022-02-27T01:20:47Z,,NONE,,"- [ ] closes #46079 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",https://api.github.com/repos/pandas-dev/pandas/issues/46114/timeline,,benjamrio,12810626,MDQ6VXNlcjEyODEwNjI2,https://avatars.githubusercontent.com/u/12810626?v=4,,https://api.github.com/users/benjamrio,https://github.com/benjamrio,https://api.github.com/users/benjamrio/followers,https://api.github.com/users/benjamrio/following{/other_user},https://api.github.com/users/benjamrio/gists{/gist_id},https://api.github.com/users/benjamrio/starred{/owner}{/repo},https://api.github.com/users/benjamrio/subscriptions,https://api.github.com/users/benjamrio/orgs,https://api.github.com/users/benjamrio/repos,https://api.github.com/users/benjamrio/events{/privacy},https://api.github.com/users/benjamrio/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46114/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46114,https://github.com/pandas-dev/pandas/pull/46114,https://github.com/pandas-dev/pandas/pull/46114.diff,https://github.com/pandas-dev/pandas/pull/46114.patch,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46112,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46112/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46112/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46112/events,https://github.com/pandas-dev/pandas/issues/46112,1146890381,I_kwDOAA0YD85EXCiN,46112,BUG: DataFrame.to_json does not take into account of time zone naive Timestamps,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-02-22T13:07:43Z,2022-02-22T13:07:43Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
>>> import pandas as pd
>>> d = {'date': [pd.to_datetime('2021-02-18')], 'instant': [pd.to_datetime('2021-02-18T11:12:13')]}
>>> df = pd.DataFrame(data=d)
>>> df.to_csv()
',date,instant\r\n0,2021-02-18,2021-02-18 11:12:13\r\n'
>>> df.to_json(orient='table',index=False)
'{""schema"":{""fields"":[{""name"":""date"",""type"":""datetime""},{""name"":""instant"",""type"":""datetime""}],""pandas_version"":""1.4.0""},""data"":[{""date"":""2021-02-18T00:00:00.000Z"",""instant"":""2021-02-18T11:12:13.000Z""}]}'
```


### Issue Description

When I give a date without a time or an datetime that is time zone naïve into a dataframe, the to_json result gives UTC time zone aware instants instead of time zone naïve instants.
`to_csv` does the right thing by only giving the date, and a time zone naïve instant.
```
2021-02-18,2021-02-18 11:12:13
```
`to_json` returns a UTC time zone aware instants for both the date and the instant.
```
{""date"":""2021-02-18T00:00:00.000Z"",""instant"":""2021-02-18T11:12:13.000Z""}
```

### Expected Behavior

I would expect the to_json to return the following
```python
>>> df.to_json(orient='table',index=False)
'{""schema"":{""fields"":[{""name"":""date"",""type"":""datetime""},{""name"":""instant"",""type"":""datetime""}],""pandas_version"":""1.4.0""},""data"":[{""date"":""2021-02-18"",""instant"":""2021-02-18T11:12:13.000""}]}'
```
Note the lack of time for the date and the lack of time zone designator for the instant.
```
{""date"":""2021-02-18"",""instant"":""2021-02-18T11:12:13.000""}
```

### Installed Versions

<details>
<pre>
INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 22.0.3
setuptools       : 56.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</pre>
</details>",https://api.github.com/repos/pandas-dev/pandas/issues/46112/timeline,,alanhowells,93594841,U_kgDOBZQk2Q,https://avatars.githubusercontent.com/u/93594841?v=4,,https://api.github.com/users/alanhowells,https://github.com/alanhowells,https://api.github.com/users/alanhowells/followers,https://api.github.com/users/alanhowells/following{/other_user},https://api.github.com/users/alanhowells/gists{/gist_id},https://api.github.com/users/alanhowells/starred{/owner}{/repo},https://api.github.com/users/alanhowells/subscriptions,https://api.github.com/users/alanhowells/orgs,https://api.github.com/users/alanhowells/repos,https://api.github.com/users/alanhowells/events{/privacy},https://api.github.com/users/alanhowells/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46112/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46111,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46111/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46111/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46111/events,https://github.com/pandas-dev/pandas/issues/46111,1146697595,I_kwDOAA0YD85EWTd7,46111,BUG: cannot use registered float16 extension dtype,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDkwMjM2OTM=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ExtensionArray', 'name': 'ExtensionArray', 'color': '6138b5', 'default': False, 'description': 'Extending pandas with custom dtypes or arrays.'}]",open,False,,[],,0,2022-02-22T10:02:36Z,2022-02-22T10:46:30Z,,MEMBER,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
>>> from pandas.api.extensions import register_extension_dtype
>>> from pandas.core.arrays.floating import FloatingDtype
>>> 
>>> 
>>> @register_extension_dtype
... class Float16Dtype(FloatingDtype):
...     type = np.float16
...     name = ""Float16""
... 
>>> pd.DataFrame([1.0, pd.NA, 2.0], dtype=""Float16"")
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File "".venv/lib/python3.8/site-packages/pandas/core/frame.py"", line 737, in __init__
    mgr = ndarray_to_mgr(
  File "".venv/lib/python3.8/site-packages/pandas/core/internals/construction.py"", line 318, in ndarray_to_mgr
    return arrays_to_mgr(values, columns, index, dtype=dtype, typ=typ)
  File "".venv/lib/python3.8/site-packages/pandas/core/internals/construction.py"", line 125, in arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "".venv/lib/python3.8/site-packages/pandas/core/internals/construction.py"", line 625, in _homogenize
    val = sanitize_array(
  File "".venv/lib/python3.8/site-packages/pandas/core/construction.py"", line 591, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
  File "".venv/lib/python3.8/site-packages/pandas/core/construction.py"", line 754, in _try_cast
    subarr = array_type(arr, dtype=dtype, copy=copy)
  File "".venv/lib/python3.8/site-packages/pandas/core/arrays/floating.py"", line 267, in _from_sequence
    return FloatingArray(values, mask)
  File "".venv/lib/python3.8/site-packages/pandas/core/arrays/floating.py"", line 258, in __init__
    raise TypeError(""FloatingArray does not support np.float16 dtype."")
TypeError: FloatingArray does not support np.float16 dtype.
```


### Issue Description

Because Pandas does not provide a Float16 extension dtype, I tried to implement it myself using register_extension_dtype.
However, it seems that there is a hard-coded error message somewhere, blocking me from using np.float16.

### Expected Behavior

I would expect users to be able to create their own dtype using np.float16  as a base.

### Installed Versions

<details>

commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-91-generic
Version          : #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.22.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 20.0.2
setuptools       : 44.0.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fastparquet      : None
fsspec           : None
gcsfs            : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>
",https://api.github.com/repos/pandas-dev/pandas/issues/46111/timeline,,DriesSchaumont,5946712,MDQ6VXNlcjU5NDY3MTI=,https://avatars.githubusercontent.com/u/5946712?v=4,,https://api.github.com/users/DriesSchaumont,https://github.com/DriesSchaumont,https://api.github.com/users/DriesSchaumont/followers,https://api.github.com/users/DriesSchaumont/following{/other_user},https://api.github.com/users/DriesSchaumont/gists{/gist_id},https://api.github.com/users/DriesSchaumont/starred{/owner}{/repo},https://api.github.com/users/DriesSchaumont/subscriptions,https://api.github.com/users/DriesSchaumont/orgs,https://api.github.com/users/DriesSchaumont/repos,https://api.github.com/users/DriesSchaumont/events{/privacy},https://api.github.com/users/DriesSchaumont/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46111/reactions,0,0,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
https://api.github.com/repos/pandas-dev/pandas/issues/46101,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46101/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46101/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46101/events,https://github.com/pandas-dev/pandas/pull/46101,1146127800,PR_kwDOAA0YD84zPtxD,46101,Add missing __finalize__ calls in indexers/iterators,"[{'id': 1539579994, 'node_id': 'MDU6TGFiZWwxNTM5NTc5OTk0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/metadata', 'name': 'metadata', 'color': '56efc9', 'default': False, 'description': '_metadata, .attrs'}]",open,False,,[],,4,2022-02-21T18:47:50Z,2022-02-27T00:07:55Z,,CONTRIBUTOR,,"- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

This PR intends to add missing `__finalize__` calls to indexers and locators (this section of the docs: https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#indexing-iteration). I went over all the methods listed in that section and in my opinion, everything should be covered after this PR.

This is generally in reference to #28283, although the methods covered here are not listed there. #19850 is also somewhat relevant.

The missing calls are only related to cases where a Series object was returned from indexing/iterating over a DataFrame. Though, I was somewhat generous with adding new test cases. Some newly added tests cases would have already passed before adding these calls, but I thought that it was still worth adding them.",https://api.github.com/repos/pandas-dev/pandas/issues/46101/timeline,,theOehrly,23384863,MDQ6VXNlcjIzMzg0ODYz,https://avatars.githubusercontent.com/u/23384863?v=4,,https://api.github.com/users/theOehrly,https://github.com/theOehrly,https://api.github.com/users/theOehrly/followers,https://api.github.com/users/theOehrly/following{/other_user},https://api.github.com/users/theOehrly/gists{/gist_id},https://api.github.com/users/theOehrly/starred{/owner}{/repo},https://api.github.com/users/theOehrly/subscriptions,https://api.github.com/users/theOehrly/orgs,https://api.github.com/users/theOehrly/repos,https://api.github.com/users/theOehrly/events{/privacy},https://api.github.com/users/theOehrly/received_events,User,False,https://api.github.com/repos/pandas-dev/pandas/issues/46101/reactions,0,0,0,0,0,0,0,0,0,False,https://api.github.com/repos/pandas-dev/pandas/pulls/46101,https://github.com/pandas-dev/pandas/pull/46101,https://github.com/pandas-dev/pandas/pull/46101.diff,https://github.com/pandas-dev/pandas/pull/46101.patch,,https://api.github.com/repos/pandas-dev/pandas/milestones/92,https://github.com/pandas-dev/pandas/milestone/92,https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels,7530006.0,MI_kwDOAA0YD84AcuYW,92.0,1.5,,jreback,953992.0,MDQ6VXNlcjk1Mzk5Mg==,https://avatars.githubusercontent.com/u/953992?v=4,,https://api.github.com/users/jreback,https://github.com/jreback,https://api.github.com/users/jreback/followers,https://api.github.com/users/jreback/following{/other_user},https://api.github.com/users/jreback/gists{/gist_id},https://api.github.com/users/jreback/starred{/owner}{/repo},https://api.github.com/users/jreback/subscriptions,https://api.github.com/users/jreback/orgs,https://api.github.com/users/jreback/repos,https://api.github.com/users/jreback/events{/privacy},https://api.github.com/users/jreback/received_events,User,False,51.0,401.0,open,2021-12-31T21:51:13Z,2022-02-28T00:39:54Z,2022-06-30T07:00:00Z,
